// Generated from catalog/catalog.json by scripts/generate-catalog.mjs.
// Do not edit by hand.

export const CATALOG_MODELS_GENERATED = [
  {
    "id": "parakeet-unified-en-0.6b",
    "name": "Parakeet Unified EN 0.6B",
    "description": "Best all-around choice for English dictation",
    "repository": "handy-computer/parakeet-unified-en-0.6b-gguf",
    "revision": "7e948f21b7bdbac698d3318db9d350f1096f3b6c",
    "license": "other",
    "family": "parakeet",
    "parameters": "0.6B",
    "languages": [
      "en"
    ],
    "capabilities": {
      "streaming": true,
      "translate": false,
      "languageDetection": false
    },
    "quant": "Q8_0",
    "filename": "parakeet-unified-en-0.6b-Q8_0.gguf",
    "size": 731357568,
    "sha256": "4b50b6dd862bf6e346929aaf4f5eaacec003bfa3f56462d6c874b41ef2f38795"
  },
  {
    "id": "nemotron-3.5-asr-streaming-0.6b",
    "name": "Nemotron Streaming 3.5",
    "description": "Fast and accurate transcription in many European languages",
    "repository": "handy-computer/nemotron-3.5-asr-streaming-0.6b-gguf",
    "revision": "6d44e540bc31b0de1dbe174a3cea87f53a7f22fb",
    "license": "other",
    "family": "nemotron",
    "parameters": "0.6B",
    "languages": [
      "en-US",
      "en-GB",
      "es-US",
      "es-ES",
      "fr-FR",
      "fr-CA",
      "it-IT",
      "pt-BR",
      "pt-PT",
      "nl-NL",
      "de-DE",
      "tr-TR",
      "ru-RU",
      "ar-AR",
      "hi-IN",
      "ja-JP",
      "ko-KR",
      "vi-VN",
      "uk-UA",
      "pl-PL",
      "sv-SE",
      "cs-CZ",
      "nb-NO",
      "da-DK",
      "bg-BG",
      "fi-FI",
      "hr-HR",
      "sk-SK",
      "zh-CN",
      "hu-HU",
      "ro-RO",
      "et-EE"
    ],
    "capabilities": {
      "streaming": true,
      "translate": false,
      "languageDetection": true
    },
    "quant": "Q8_0",
    "filename": "nemotron-3.5-asr-streaming-0.6b-Q8_0.gguf",
    "size": 751094240,
    "sha256": "b94545b313b3223fda7b2857a52681da813935c2127643d1e9ff0c23d988089c"
  },
  {
    "id": "canary-180m-flash",
    "name": "Canary 180M Flash",
    "description": "Tiny, fast, and runs well on any hardware",
    "repository": "handy-computer/canary-180m-flash-gguf",
    "revision": "b147f9dc52b59f0998e410540a84727bd86457fd",
    "license": "cc-by-4.0",
    "family": "canary",
    "parameters": "180M",
    "languages": [
      "en",
      "de",
      "es",
      "fr"
    ],
    "capabilities": {
      "streaming": false,
      "translate": true,
      "languageDetection": false
    },
    "quant": "Q8_0",
    "filename": "canary-180m-flash-Q8_0.gguf",
    "size": 218447552,
    "sha256": "e13c7f5d0952b056a027cfffec13e3a3a134d1608babed24f983568f141e297c"
  },
  {
    "id": "cohere-transcribe-03-2026",
    "name": "Cohere Transcribe",
    "description": "Consistently strong in many languages, best for Greek and Polish",
    "repository": "handy-computer/cohere-transcribe-03-2026-gguf",
    "revision": "dfa4adebb64f3076b7b6b90b721275cc069cb421",
    "license": "apache-2.0",
    "family": "cohere",
    "parameters": "2.0B",
    "languages": [
      "en",
      "fr",
      "de",
      "es",
      "it",
      "pt",
      "nl",
      "pl",
      "el",
      "ar",
      "ja",
      "zh",
      "vi",
      "ko"
    ],
    "capabilities": {
      "streaming": false,
      "translate": false,
      "languageDetection": false
    },
    "quant": "Q8_0",
    "filename": "cohere-transcribe-03-2026-Q8_0.gguf",
    "size": 2410655232,
    "sha256": "931916663432fd895423a4291a8400221802b288967ca2d435fc5e3141c9e71e"
  },
  {
    "id": "whisper-medium",
    "name": "Whisper Medium",
    "description": "Broadest language support, but may run a bit slow",
    "repository": "handy-computer/whisper-medium-gguf",
    "revision": "ec78f06fded51aa82cde751678b78f76f78c8b7f",
    "license": "apache-2.0",
    "family": "whisper",
    "parameters": "764M",
    "languages": [
      "af",
      "am",
      "ar",
      "as",
      "az",
      "ba",
      "be",
      "bg",
      "bn",
      "bo",
      "br",
      "bs",
      "ca",
      "cs",
      "cy",
      "da",
      "de",
      "el",
      "en",
      "es",
      "et",
      "eu",
      "fa",
      "fi",
      "fo",
      "fr",
      "gl",
      "gu",
      "haw",
      "ha",
      "he",
      "hi",
      "hr",
      "ht",
      "hu",
      "hy",
      "id",
      "is",
      "it",
      "ja",
      "jw",
      "ka",
      "kk",
      "km",
      "kn",
      "ko",
      "la",
      "lb",
      "ln",
      "lo",
      "lt",
      "lv",
      "mg",
      "mi",
      "mk",
      "ml",
      "mn",
      "mr",
      "ms",
      "mt",
      "my",
      "ne",
      "nl",
      "nn",
      "no",
      "oc",
      "pa",
      "pl",
      "ps",
      "pt",
      "ro",
      "ru",
      "sa",
      "sd",
      "si",
      "sk",
      "sl",
      "sn",
      "so",
      "sq",
      "sr",
      "su",
      "sv",
      "sw",
      "ta",
      "te",
      "tg",
      "th",
      "tk",
      "tl",
      "tr",
      "tt",
      "uk",
      "ur",
      "uz",
      "vi",
      "yi",
      "yo",
      "zh"
    ],
    "capabilities": {
      "streaming": false,
      "translate": true,
      "languageDetection": true
    },
    "quant": "Q8_0",
    "filename": "whisper-medium-Q8_0.gguf",
    "size": 831538144,
    "sha256": "09e6a65e7de377aa5b10bae24608bc6f8ca2ed04b3993ef10d4a02bcd9a82adf"
  },
  {
    "id": "Voxtral-Mini-4B-Realtime-2602",
    "name": "Voxtral Mini 4B Realtime",
    "description": "Multilingual, very accurate in Italian and Spanish. Best on Apple Silicon or discrete GPUs",
    "repository": "handy-computer/Voxtral-Mini-4B-Realtime-2602-gguf",
    "revision": "b3e1c979e3775cbd0a49a65878a0ec7f06789ed7",
    "license": "apache-2.0",
    "family": "voxtral",
    "parameters": "4.8B",
    "languages": [
      "en",
      "fr",
      "es",
      "de",
      "ru",
      "zh",
      "ja",
      "it",
      "pt",
      "nl",
      "ar",
      "hi",
      "ko"
    ],
    "capabilities": {
      "streaming": true,
      "translate": false,
      "languageDetection": true
    },
    "quant": "Q8_0",
    "filename": "Voxtral-Mini-4B-Realtime-2602-Q8_0.gguf",
    "size": 4731791648,
    "sha256": "6fb22249463c1e7a600d920ad732e2dd0a231510e9db59fb8061d3d1d48d0c67"
  },
  {
    "id": "parakeet-tdt-0.6b-v3",
    "name": "Parakeet TDT 0.6B v3",
    "description": "Fast and accurate, great overall multilingual pick",
    "repository": "handy-computer/parakeet-tdt-0.6b-v3-gguf",
    "revision": "85ac09ea12fc4b1112fa76810059364bc6adc9de",
    "license": "cc-by-4.0",
    "family": "parakeet",
    "parameters": "0.6B",
    "languages": [
      "bg",
      "hr",
      "cs",
      "da",
      "nl",
      "en",
      "et",
      "fi",
      "fr",
      "de",
      "el",
      "hu",
      "it",
      "lv",
      "lt",
      "mt",
      "pl",
      "pt",
      "ro",
      "ru",
      "sk",
      "sl",
      "es",
      "sv",
      "uk"
    ],
    "capabilities": {
      "streaming": false,
      "translate": false,
      "languageDetection": true
    },
    "quant": "Q8_0",
    "filename": "parakeet-tdt-0.6b-v3-Q8_0.gguf",
    "size": 739508576,
    "sha256": "5859f77944efcd8eafa23a6350731960b2b55b2203df51f319665c807d802cc7"
  },
  {
    "id": "parakeet-tdt-0.6b-v2",
    "name": "Parakeet TDT 0.6B v2",
    "description": "Excellent English only model, runs on any hardware",
    "repository": "handy-computer/parakeet-tdt-0.6b-v2-gguf",
    "revision": "07cee0616125a08ef619729bb47f40ef747e4bc4",
    "license": "cc-by-4.0",
    "family": "parakeet",
    "parameters": "0.6B",
    "languages": [
      "en"
    ],
    "capabilities": {
      "streaming": false,
      "translate": false,
      "languageDetection": false
    },
    "quant": "Q8_0",
    "filename": "parakeet-tdt-0.6b-v2-Q8_0.gguf",
    "size": 729574912,
    "sha256": "f0d0e99cebb6d3b83f1f7069b82b5d3c2e39a54545b0da039cb4bafd9c4e5caa"
  },
  {
    "id": "Qwen3-ASR-0.6B",
    "name": "Qwen3-ASR 0.6B",
    "description": "Best for Chinese, Cantonese, and Asian languages with English",
    "repository": "handy-computer/Qwen3-ASR-0.6B-gguf",
    "revision": "e4e16599b900eb0cb36e524514756bb92eb092b7",
    "license": "apache-2.0",
    "family": "qwen3",
    "parameters": "782M",
    "languages": [
      "zh",
      "en",
      "yue",
      "ar",
      "de",
      "fr",
      "es",
      "pt",
      "id",
      "it",
      "ko",
      "ru",
      "th",
      "vi",
      "ja",
      "tr",
      "hi",
      "ms",
      "nl",
      "sv",
      "da",
      "fi",
      "pl",
      "cs",
      "fil",
      "fa",
      "el",
      "ro",
      "hu",
      "mk"
    ],
    "capabilities": {
      "streaming": false,
      "translate": false,
      "languageDetection": true
    },
    "quant": "Q8_0",
    "filename": "Qwen3-ASR-0.6B-Q8_0.gguf",
    "size": 850423456,
    "sha256": "f081b2d5e23bd669d92cc331d722a8a0681943b8e6f34b48996fd5c319b5acd8"
  },
  {
    "id": "Fun-ASR-MLT-Nano-2512",
    "name": "Fun-ASR Nano Multilingual",
    "description": "Best for Japanese, good at Thai, Indonesian, Malay",
    "repository": "handy-computer/Fun-ASR-MLT-Nano-2512-gguf",
    "revision": "0b8f9c7bc545a219658aeb1dd4eeaa55d1cf89f3",
    "license": "apache-2.0",
    "family": "fun",
    "parameters": "985M",
    "languages": [
      "zh",
      "en",
      "yue",
      "ja",
      "ko",
      "vi",
      "id",
      "th",
      "ms",
      "tl",
      "ar",
      "hi",
      "bg",
      "hr",
      "cs",
      "da",
      "nl",
      "et",
      "fi",
      "el",
      "hu",
      "ga",
      "lv",
      "lt",
      "mt",
      "pl",
      "pt",
      "ro",
      "sk",
      "sl",
      "sv"
    ],
    "capabilities": {
      "streaming": false,
      "translate": false,
      "languageDetection": false
    },
    "quant": "Q8_0",
    "filename": "Fun-ASR-MLT-Nano-2512-Q8_0.gguf",
    "size": 891271232,
    "sha256": "d12476d8d9f2baa0ebf738fa955fa05ed33a654f1567289033a810c45d9d9002"
  },
  {
    "id": "canary-1b-v2",
    "name": "Canary 1B v2",
    "description": "Most accurate small model for European languages",
    "repository": "handy-computer/canary-1b-v2-gguf",
    "revision": "58d13c2c0102229aad45f7e19a77ddc42b41dd9a",
    "license": "cc-by-4.0",
    "family": "canary",
    "parameters": "1B",
    "languages": [
      "bg",
      "hr",
      "cs",
      "da",
      "nl",
      "en",
      "et",
      "fi",
      "fr",
      "de",
      "el",
      "hu",
      "it",
      "lv",
      "lt",
      "mt",
      "pl",
      "pt",
      "ro",
      "sk",
      "sl",
      "es",
      "sv",
      "ru",
      "uk"
    ],
    "capabilities": {
      "streaming": false,
      "translate": true,
      "languageDetection": false
    },
    "quant": "Q8_0",
    "filename": "canary-1b-v2-Q8_0.gguf",
    "size": 1144290016,
    "sha256": "224f83d1bc487b3303b495a7d6874912fdece93de19d1a04b550829c30a5d289"
  },
  {
    "id": "canary-qwen-2.5b",
    "name": "Canary-Qwen 2.5B",
    "description": "Very accurate English. Slow without a GPU.",
    "repository": "handy-computer/canary-qwen-2.5b-gguf",
    "revision": "3370d4e2f28cc70eea79dfc9f2f43fb91eef3163",
    "license": "cc-by-4.0",
    "family": "canary",
    "parameters": "2.5B",
    "languages": [
      "en"
    ],
    "capabilities": {
      "streaming": false,
      "translate": false,
      "languageDetection": false
    },
    "quant": "Q8_0",
    "filename": "canary-qwen-2.5b-Q8_0.gguf",
    "size": 2797548928,
    "sha256": "d89aad1285d5bd5aa441c464d3a4cf37bd5474f70705408e71558d8627415b34"
  },
  {
    "id": "cohere-transcribe-arabic-07-2026",
    "name": "Cohere Transcribe Arabic",
    "description": "Best for Arabic and Arabic/English speakers",
    "repository": "handy-computer/cohere-transcribe-arabic-07-2026-gguf",
    "revision": "715cbe09ca9b60fc1e497db1e4478fa9fcf4ac21",
    "license": "apache-2.0",
    "family": "cohere",
    "parameters": "2.0B",
    "languages": [
      "en",
      "ar"
    ],
    "capabilities": {
      "streaming": false,
      "translate": false,
      "languageDetection": false
    },
    "quant": "Q8_0",
    "filename": "cohere-transcribe-arabic-07-2026-Q8_0.gguf",
    "size": 2410655136,
    "sha256": "910de5c9c57f9fd8a280e1701f9cd96f63768878c1ca9e4ecf23638a5e0fef16"
  },
  {
    "id": "Fun-ASR-Nano-2512",
    "name": "Fun-ASR Nano",
    "description": "Good for Mandarin, English, Japanese",
    "repository": "handy-computer/Fun-ASR-Nano-2512-gguf",
    "revision": "30360f003f99929c1e25c3f6222d02eccb04663c",
    "license": "apache-2.0",
    "family": "fun",
    "parameters": "985M",
    "languages": [
      "zh",
      "en",
      "ja"
    ],
    "capabilities": {
      "streaming": false,
      "translate": false,
      "languageDetection": false
    },
    "quant": "Q8_0",
    "filename": "Fun-ASR-Nano-2512-Q8_0.gguf",
    "size": 891270912,
    "sha256": "681caef6df15a2c0e153b40ca7fe4087fdf65751fa5e6fe605d8a75dff969e61"
  },
  {
    "id": "gigaam-v3-e2e-ctc",
    "name": "GigaAM v3 E2E-CTC",
    "description": "Russian only.",
    "repository": "handy-computer/gigaam-v3-e2e-ctc-gguf",
    "revision": "075dff81f843cf23d22b4ce943ffdc4dd8650cd7",
    "license": "mit",
    "family": "gigaam",
    "parameters": "221M",
    "languages": [
      "ru"
    ],
    "capabilities": {
      "streaming": false,
      "translate": false,
      "languageDetection": false
    },
    "quant": "Q8_0",
    "filename": "gigaam-v3-e2e-ctc-Q8_0.gguf",
    "size": 272151136,
    "sha256": "9ccce4750dc813a493d96ca15ee251712bedec15ac9a02fa3d2bd732f08ae5eb"
  },
  {
    "id": "gigaam-v3-e2e-rnnt",
    "name": "GigaAM v3 E2E-RNN-T",
    "description": "Best for Russian dictation. English may be unreliable.",
    "repository": "handy-computer/gigaam-v3-e2e-rnnt-gguf",
    "revision": "f719d70812344f4d0fb8c11c0887b190501a7465",
    "license": "mit",
    "family": "gigaam",
    "parameters": "223M",
    "languages": [
      "ru"
    ],
    "capabilities": {
      "streaming": false,
      "translate": false,
      "languageDetection": false
    },
    "quant": "Q8_0",
    "filename": "gigaam-v3-e2e-rnnt-Q8_0.gguf",
    "size": 273724832,
    "sha256": "78d63b47723b7f8d78c6113a6ef983b5a86e2a86f6c273e1f5cb6967b1c4467a"
  },
  {
    "id": "granite-speech-4.1-2b",
    "name": "Granite Speech 4.1 2B",
    "description": "Accurate with translation support. Best with GPU",
    "repository": "handy-computer/granite-speech-4.1-2b-gguf",
    "revision": "58e7710fd7039ded5a185668eef5f71ca5d9d919",
    "license": "apache-2.0",
    "family": "granite",
    "parameters": "2.3B",
    "languages": [
      "en",
      "fr",
      "de",
      "es",
      "pt",
      "ja"
    ],
    "capabilities": {
      "streaming": false,
      "translate": true,
      "languageDetection": false
    },
    "quant": "Q8_0",
    "filename": "granite-speech-4.1-2b-Q8_0.gguf",
    "size": 2559878848,
    "sha256": "8c0b2dce2861feb1dba91e9d59f2ab4a9c23ad808bff86465151576e096ec7a6"
  },
  {
    "id": "medasr",
    "name": "MedASR",
    "description": "For clinicians dictating notes. Poor on general speech",
    "repository": "handy-computer/medasr-gguf",
    "revision": "6f481df085bb50ae922cea918fb578e664237126",
    "license": "other",
    "family": "medasr",
    "parameters": "105M",
    "languages": [
      "en"
    ],
    "capabilities": {
      "streaming": false,
      "translate": false,
      "languageDetection": false
    },
    "quant": "Q8_0",
    "filename": "medasr-Q8_0.gguf",
    "size": 127712448,
    "sha256": "5a391a2154416b96241b829ac2c7eed8b64d197f00372512c9bbf63f4849c978"
  },
  {
    "id": "parakeet-tdt_ctc-110m",
    "name": "Parakeet TDT-CTC 110M",
    "description": "Tiny English model, virtually instant even on CPU",
    "repository": "handy-computer/parakeet-tdt_ctc-110m-gguf",
    "revision": "9d66d34f9e1594075c5dd72c90c0f4c321b29f21",
    "license": "cc-by-4.0",
    "family": "parakeet",
    "parameters": "110M",
    "languages": [
      "en"
    ],
    "capabilities": {
      "streaming": false,
      "translate": false,
      "languageDetection": false
    },
    "quant": "Q8_0",
    "filename": "parakeet-tdt_ctc-110m-Q8_0.gguf",
    "size": 135373280,
    "sha256": "7dd44c74a331d788a4e5f8b16913b3feb29ced22cf5613aad0e0f6cd30516296"
  },
  {
    "id": "multitalker-parakeet-streaming-0.6b-v1",
    "name": "Parakeet Multitalker EN",
    "description": "For overlapping speakers in meetings, not for solo dictation",
    "repository": "handy-computer/multitalker-parakeet-streaming-0.6b-v1-gguf",
    "revision": "0314bc0d2f4be9a0d79fa5eeb36ad1f3962cfcbb",
    "license": "other",
    "family": "parakeet",
    "parameters": "0.6B",
    "languages": [
      "en"
    ],
    "capabilities": {
      "streaming": true,
      "translate": false,
      "languageDetection": false
    },
    "quant": "Q8_0",
    "filename": "multitalker-parakeet-streaming-0.6b-v1-Q8_0.gguf",
    "size": 734123712,
    "sha256": "4748deea0222eb9057ebdac1679eebb970bbe882ee10a96ae34596ffe83615c7"
  },
  {
    "id": "Qwen3-ASR-1.7B",
    "name": "Qwen3-ASR 1.7B",
    "description": "Top accuracy across languages. Best on Apple Silicon or a GPU",
    "repository": "handy-computer/Qwen3-ASR-1.7B-gguf",
    "revision": "92282af1610a2db19d66f2bef1e260f5deca782d",
    "license": "apache-2.0",
    "family": "qwen3",
    "parameters": "2.0B",
    "languages": [
      "zh",
      "en",
      "yue",
      "ar",
      "de",
      "fr",
      "es",
      "pt",
      "id",
      "it",
      "ko",
      "ru",
      "th",
      "vi",
      "ja",
      "tr",
      "hi",
      "ms",
      "nl",
      "sv",
      "da",
      "fi",
      "pl",
      "cs",
      "fil",
      "fa",
      "el",
      "ro",
      "hu",
      "mk"
    ],
    "capabilities": {
      "streaming": false,
      "translate": false,
      "languageDetection": true
    },
    "quant": "Q8_0",
    "filename": "Qwen3-ASR-1.7B-Q8_0.gguf",
    "size": 2185030624,
    "sha256": "9a0d81792dfea2d5f278b8a63deb3ea6e02139ce42c2301f32ea19c4f77526b7"
  },
  {
    "id": "SenseVoiceSmall",
    "name": "SenseVoice Small",
    "description": "Instant Mandarin, Japanese, Korean on any machine. Weak Cantonese",
    "repository": "handy-computer/SenseVoiceSmall-gguf",
    "revision": "4a08b8e900b38a977e32eb08d5d0697d6e72ba04",
    "license": "other",
    "family": "sensevoice",
    "parameters": "234M",
    "languages": [
      "zh",
      "yue",
      "en",
      "ja",
      "ko"
    ],
    "capabilities": {
      "streaming": false,
      "translate": false,
      "languageDetection": true
    },
    "quant": "Q8_0",
    "filename": "SenseVoiceSmall-Q8_0.gguf",
    "size": 252684608,
    "sha256": "6c759ee4c9748c9b3f7a5a60ca74f0f7e685fb9d45d1378fce7cfd62f59adf29"
  },
  {
    "id": "Voxtral-Mini-3B-2507",
    "name": "Voxtral Mini 3B",
    "description": "Accurate with translation support. Best on Apple Silicon or a GPU.",
    "repository": "handy-computer/Voxtral-Mini-3B-2507-gguf",
    "revision": "5690205813042c07cbaa86d2a9dcc585fcd31304",
    "license": "apache-2.0",
    "family": "voxtral",
    "parameters": "4.7B",
    "languages": [
      "en",
      "fr",
      "de",
      "es",
      "it",
      "pt",
      "nl",
      "hi"
    ],
    "capabilities": {
      "streaming": false,
      "translate": true,
      "languageDetection": true
    },
    "quant": "Q8_0",
    "filename": "Voxtral-Mini-3B-2507-Q8_0.gguf",
    "size": 5000084128,
    "sha256": "06b4dd04e32953ccab0d417125bdd728ec031431596ed5e80123c3c66f29ddc2"
  },
  {
    "id": "whisper-small",
    "name": "Whisper Small",
    "description": "Wide language support in a relatively small model.",
    "repository": "handy-computer/whisper-small-gguf",
    "revision": "c0214bd34be9296695486f838e0142f900803159",
    "license": "apache-2.0",
    "family": "whisper",
    "parameters": "242M",
    "languages": [
      "af",
      "am",
      "ar",
      "as",
      "az",
      "ba",
      "be",
      "bg",
      "bn",
      "bo",
      "br",
      "bs",
      "ca",
      "cs",
      "cy",
      "da",
      "de",
      "el",
      "en",
      "es",
      "et",
      "eu",
      "fa",
      "fi",
      "fo",
      "fr",
      "gl",
      "gu",
      "haw",
      "ha",
      "he",
      "hi",
      "hr",
      "ht",
      "hu",
      "hy",
      "id",
      "is",
      "it",
      "ja",
      "jw",
      "ka",
      "kk",
      "km",
      "kn",
      "ko",
      "la",
      "lb",
      "ln",
      "lo",
      "lt",
      "lv",
      "mg",
      "mi",
      "mk",
      "ml",
      "mn",
      "mr",
      "ms",
      "mt",
      "my",
      "ne",
      "nl",
      "nn",
      "no",
      "oc",
      "pa",
      "pl",
      "ps",
      "pt",
      "ro",
      "ru",
      "sa",
      "sd",
      "si",
      "sk",
      "sl",
      "sn",
      "so",
      "sq",
      "sr",
      "su",
      "sv",
      "sw",
      "ta",
      "te",
      "tg",
      "th",
      "tk",
      "tl",
      "tr",
      "tt",
      "uk",
      "ur",
      "uz",
      "vi",
      "yi",
      "yo",
      "zh"
    ],
    "capabilities": {
      "streaming": false,
      "translate": true,
      "languageDetection": true
    },
    "quant": "Q8_0",
    "filename": "whisper-small-Q8_0.gguf",
    "size": 269751136,
    "sha256": "9b9c8811bbcc82a7766f0fb0925614bdacb0923b2cc630daeac17108b655b860"
  },
  {
    "id": "whisper-large-v3-turbo",
    "name": "Whisper Large v3 Turbo",
    "description": "Accurate in many languages. Slow without a GPU",
    "repository": "handy-computer/whisper-large-v3-turbo-gguf",
    "revision": "5eaf945c7978e564bae5b28a5b1639dd93c2bfb1",
    "license": "apache-2.0",
    "family": "whisper",
    "parameters": "809M",
    "languages": [
      "af",
      "am",
      "ar",
      "as",
      "az",
      "ba",
      "be",
      "bg",
      "bn",
      "bo",
      "br",
      "bs",
      "ca",
      "cs",
      "cy",
      "da",
      "de",
      "el",
      "en",
      "es",
      "et",
      "eu",
      "fa",
      "fi",
      "fo",
      "fr",
      "gl",
      "gu",
      "haw",
      "ha",
      "he",
      "hi",
      "hr",
      "ht",
      "hu",
      "hy",
      "id",
      "is",
      "it",
      "ja",
      "jw",
      "ka",
      "kk",
      "km",
      "kn",
      "ko",
      "la",
      "lb",
      "ln",
      "lo",
      "lt",
      "lv",
      "mg",
      "mi",
      "mk",
      "ml",
      "mn",
      "mr",
      "ms",
      "mt",
      "my",
      "ne",
      "nl",
      "nn",
      "no",
      "oc",
      "pa",
      "pl",
      "ps",
      "pt",
      "ro",
      "ru",
      "sa",
      "sd",
      "si",
      "sk",
      "sl",
      "sn",
      "so",
      "sq",
      "sr",
      "su",
      "sv",
      "sw",
      "ta",
      "te",
      "tg",
      "th",
      "tk",
      "tl",
      "tr",
      "tt",
      "uk",
      "ur",
      "uz",
      "vi",
      "yi",
      "yo",
      "yue",
      "zh"
    ],
    "capabilities": {
      "streaming": false,
      "translate": false,
      "languageDetection": true
    },
    "quant": "Q8_0",
    "filename": "whisper-large-v3-turbo-Q8_0.gguf",
    "size": 886381760,
    "sha256": "b2e30cc286bc9f3aba4db9099fc7403543497c05ce7100d0d83091ddfd25a183"
  },
  {
    "id": "Breeze-ASR-25",
    "name": "Breeze-ASR-25",
    "description": "Taiwan Mandarin with English mixed in. Traditional script, no punctuation",
    "repository": "handy-computer/Breeze-ASR-25-gguf",
    "revision": "1e5e8d7295110e1e14e305e9cf7411d82711beaa",
    "license": "apache-2.0",
    "family": "whisper",
    "parameters": "1.5B",
    "languages": [
      "af",
      "am",
      "ar",
      "as",
      "az",
      "ba",
      "be",
      "bg",
      "bn",
      "bo",
      "br",
      "bs",
      "ca",
      "cs",
      "cy",
      "da",
      "de",
      "el",
      "en",
      "es",
      "et",
      "eu",
      "fa",
      "fi",
      "fo",
      "fr",
      "gl",
      "gu",
      "haw",
      "ha",
      "he",
      "hi",
      "hr",
      "ht",
      "hu",
      "hy",
      "id",
      "is",
      "it",
      "ja",
      "jw",
      "ka",
      "kk",
      "km",
      "kn",
      "ko",
      "la",
      "lb",
      "ln",
      "lo",
      "lt",
      "lv",
      "mg",
      "mi",
      "mk",
      "ml",
      "mn",
      "mr",
      "ms",
      "mt",
      "my",
      "ne",
      "nl",
      "nn",
      "no",
      "oc",
      "pa",
      "pl",
      "ps",
      "pt",
      "ro",
      "ru",
      "sa",
      "sd",
      "si",
      "sk",
      "sl",
      "sn",
      "so",
      "sq",
      "sr",
      "su",
      "sv",
      "sw",
      "ta",
      "te",
      "tg",
      "th",
      "tk",
      "tl",
      "tr",
      "tt",
      "uk",
      "ur",
      "uz",
      "vi",
      "yi",
      "yo",
      "zh"
    ],
    "capabilities": {
      "streaming": false,
      "translate": true,
      "languageDetection": true
    },
    "quant": "Q8_0",
    "filename": "Breeze-ASR-25-Q8_0.gguf",
    "size": 1667964224,
    "sha256": "1650c163cd1623d13b585368ffd87d7e669c5ff23014511e0fa91bb4ce994756"
  },
  {
    "id": "whisper-large-v3",
    "name": "Whisper Large v3",
    "description": "Most languages at usable accuracy. Best on Apple Silicon or a GPU.",
    "repository": "handy-computer/whisper-large-v3-gguf",
    "revision": "e3e29bee6389c7da4a141406f07bb80ddac5337c",
    "license": "apache-2.0",
    "family": "whisper",
    "parameters": "1.5B",
    "languages": [
      "af",
      "am",
      "ar",
      "as",
      "az",
      "ba",
      "be",
      "bg",
      "bn",
      "bo",
      "br",
      "bs",
      "ca",
      "cs",
      "cy",
      "da",
      "de",
      "el",
      "en",
      "es",
      "et",
      "eu",
      "fa",
      "fi",
      "fo",
      "fr",
      "gl",
      "gu",
      "haw",
      "ha",
      "he",
      "hi",
      "hr",
      "ht",
      "hu",
      "hy",
      "id",
      "is",
      "it",
      "ja",
      "jw",
      "ka",
      "kk",
      "km",
      "kn",
      "ko",
      "la",
      "lb",
      "ln",
      "lo",
      "lt",
      "lv",
      "mg",
      "mi",
      "mk",
      "ml",
      "mn",
      "mr",
      "ms",
      "mt",
      "my",
      "ne",
      "nl",
      "nn",
      "no",
      "oc",
      "pa",
      "pl",
      "ps",
      "pt",
      "ro",
      "ru",
      "sa",
      "sd",
      "si",
      "sk",
      "sl",
      "sn",
      "so",
      "sq",
      "sr",
      "su",
      "sv",
      "sw",
      "ta",
      "te",
      "tg",
      "th",
      "tk",
      "tl",
      "tr",
      "tt",
      "uk",
      "ur",
      "uz",
      "vi",
      "yi",
      "yo",
      "yue",
      "zh"
    ],
    "capabilities": {
      "streaming": false,
      "translate": true,
      "languageDetection": true
    },
    "quant": "Q8_0",
    "filename": "whisper-large-v3-Q8_0.gguf",
    "size": 1668741440,
    "sha256": "2fa1a5f179f8a511a53e2108db270aa4af3ce08cd976af4180e2854666bb4ba3"
  }
] as const;
