import * as fs from "node:fs";
import * as path from "node:path";

/**
 * Ground truth for `pi-hashline-edit-pro`'s line anchors (#2423 review round 1,
 * finding F1).
 *
 * `tests/fixtures/hashline-edit-pro/anchor-vectors.json` was generated by
 * running the EXTENSION's own `_lineHashesPure` with the real `xxhash-wasm` —
 * see the sibling `generate-anchor-vectors.mjs` and the `upstream` block in the
 * JSON for the commit.
 *
 * Tests take their anchors from here rather than from
 * `clients/hashline-anchor.ts`. Two reasons, both deliberate:
 *
 * 1. A test that asks the module under test what the right answer is proves
 *    nothing. These anchors come from the other project's arithmetic.
 * 2. Importing the production module would make every case in a file red with
 *    a module-resolution error when the module is absent, which is a much
 *    weaker red-first proof than an assertion failure.
 */
interface HashlineAnchorVectors {
	upstream: {
		repo: string;
		branch: string;
		commit: string;
		generatedWith: string;
		source: string[];
	};
	xxh32: Array<{ input: string; h32: number }>;
	lineAnchors: Record<string, { content: string; hashes: string[] }>;
	/**
	 * One simulated edit per entry, run through the extension's own
	 * `mapStableHashes` (review round 3, finding F1). `hashesAfter` is the
	 * anchor list the extension's hash store SERVES after that edit — the
	 * anchors an agent quotes back — which is not what recomputing from the
	 * file's content produces for a duplicate-content line.
	 */
	storeCarried: Record<string, HashlineStoreCarried>;
}

export interface HashlineStoreCarried {
	description: string;
	before: string;
	after: string;
	removedHashes: string[];
	hashesBefore: string[];
	hashesAfter: string[];
}

let cached: HashlineAnchorVectors | undefined;

function loadHashlineAnchorVectors(): HashlineAnchorVectors {
	if (cached) return cached;
	cached = JSON.parse(
		fs.readFileSync(
			path.resolve(
				import.meta.dirname,
				"..",
				"fixtures",
				"hashline-edit-pro",
				"anchor-vectors.json",
			),
			"utf8",
		),
	) as HashlineAnchorVectors;
	return cached;
}

/** One named fixture file: its content and the anchor of each of its lines. */
export function hashlineFixture(name: string): {
	content: string;
	/** `anchorFor(1)` is the anchor of line 1. */
	anchorFor: (line: number) => string;
	lineCount: number;
} {
	const entry = loadHashlineAnchorVectors().lineAnchors[name];
	if (!entry) throw new Error(`unknown hashline fixture "${name}"`);
	return {
		content: entry.content,
		anchorFor: (line: number) => {
			const anchor = entry.hashes[line - 1];
			if (anchor === undefined)
				throw new Error(`fixture "${name}" has no line ${line}`);
			return anchor;
		},
		lineCount: entry.hashes.length,
	};
}

/**
 * One store-carried scenario: the file AFTER one edit, plus the anchors the
 * extension's store hands out for it. `carriedAnchorFor(10)` is the anchor
 * upstream attached to line 10 — which is the line pi-lens must either name
 * correctly or refuse to name at all.
 */
export function hashlineStoreCarried(name: string): HashlineStoreCarried & {
	afterLines: string[];
	carriedAnchorFor: (line: number) => string;
} {
	const entry = loadHashlineAnchorVectors().storeCarried?.[name];
	if (!entry) throw new Error(`unknown store-carried scenario "${name}"`);
	const afterLines = entry.after.endsWith("\n")
		? entry.after.split("\n").slice(0, -1)
		: entry.after.split("\n");
	return {
		...entry,
		afterLines,
		carriedAnchorFor: (line: number) => {
			const anchor = entry.hashesAfter[line - 1];
			if (anchor === undefined)
				throw new Error(`scenario "${name}" has no line ${line}`);
			return anchor;
		},
	};
}
