#!/usr/bin/env node
import { posix, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { createLedgerCli, executeLedgerCli } from "../../shared/run-ledger.mjs";

const TYPES = new Set(["run.started", "ticket.started", "attempt.started", "implementation.applied", "mechanical.verification.recorded", "acceptance.started", "criterion.checked", "acceptance.closed", "failure.raised", "repair.applied", "failure.verification.recorded", "attempt.closed", "human.decided", "run.blocked", "run.resumed", "commit.recorded", "tracker.recorded", "ticket.closed", "run.closed"]);
const ACTORS = ["parent", "builder", "repairer", "acceptance-verifier"];
const assert = (condition, message) => { if (!condition) throw new Error(message); };
const object = (value, field) => { assert(value && typeof value === "object" && !Array.isArray(value), `${field} must be an object`); return value; };
const string = (value, field, empty = false) => assert(typeof value === "string" && (empty || value.trim()), `${field} must be ${empty ? "a string" : "a non-empty string"}`);
const integer = (value, field) => assert(Number.isInteger(value) && value > 0, `${field} must be a positive integer`);
const boolean = (value, field, expected) => assert(value === expected, `${field} must be ${expected}`);
const oneOf = (value, values, field) => assert(values.includes(value), `${field} must be one of: ${values.join(", ")}`);
const array = (value, field, nonempty = false) => assert(Array.isArray(value) && (!nonempty || value.length), `${field} must be ${nonempty ? "a non-empty" : "an"} array`);
const strings = (value, field, nonempty = false) => { array(value, field, nonempty); value.forEach((item, index) => string(item, `${field}[${index}]`)); };
const exact = (value, allowed, field) => { for (const key of Object.keys(value)) assert(allowed.includes(key), `${field}.${key} is not allowed`); for (const key of allowed) assert(key in value, `${field}.${key} is required`); };
const sameSet = (left, right) => left.length === right.length && [...left].sort().every((value, index) => value === [...right].sort()[index]);
const sameTracker = (left, right) => ["provider", "repository", "number", "url", "title"].every((key) => left[key] === right[key]);
const failureId = (value, field) => assert(/^BF-\d{3,4}$/.test(value), `${field} must match BF-001`);
const repositoryPath = (value, field) => {
  string(value, field); assert(!value.startsWith("/") && !value.includes("\\"), `${field} must be repository-relative`);
  const normalized = posix.normalize(value); assert(normalized !== "." && normalized !== ".." && !normalized.startsWith("../") && normalized === value.replace(/\/$/, ""), `${field} must be a normalized repository-relative path`); return normalized;
};
const within = (path, roots) => roots.some((root) => path === root || path.startsWith(`${root}/`));
const assertTicketPaths = (paths, charter, field) => paths.forEach((value) => {
  const path = repositoryPath(value, field); assert(within(path, charter.mutablePaths), `${field} is outside mutable scope: ${path}`); assert(!within(path, charter.userOwnedPaths), `${field} includes user-owned path: ${path}`);
});

function evidence(value, field) {
  array(value, field, true);
  value.forEach((item, index) => {
    object(item, `${field}[${index}]`);
    exact(item, item.sha256 === undefined ? ["kind", "ref"] : ["kind", "ref", "sha256"], `${field}[${index}]`);
    oneOf(item.kind, ["capture", "command", "file", "note"], `${field}[${index}].kind`);
    string(item.ref, `${field}[${index}].ref`);
    if (["capture", "file"].includes(item.kind)) assert(!item.ref.startsWith("/") && !item.ref.split(/[\\/]/).includes(".."), `${field}[${index}].ref must stay inside the run directory`);
    if (item.sha256 !== undefined) assert(/^[a-f0-9]{64}$/.test(item.sha256), `${field}[${index}].sha256 must be lowercase SHA-256`);
  });
}
function tracker(value, field, expectedState) {
  object(value, field); exact(value, ["provider", "repository", "number", "url", "title", "state"], field);
  for (const key of ["provider", "repository", "url", "title"]) string(value[key], `${field}.${key}`);
  integer(value.number, `${field}.number`); oneOf(value.state, ["open", "closed"], `${field}.state`);
  if (expectedState) assert(value.state === expectedState, `${field}.state must be ${expectedState}`);
}
function validateCharter(value) {
  object(value, "run.started.charter"); exact(value, ["ticket", "ticketBody", "ticketComments", "parent", "parentBody", "parentComments", "userVisibleOutcome", "criteria", "testSeams", "mechanicalChecks", "mutablePaths", "safety", "outOfScope", "startingWorktree", "userOwnedPaths"], "run.started.charter");
  tracker(value.ticket, "charter.ticket", "open"); string(value.ticketBody, "charter.ticketBody"); strings(value.ticketComments, "charter.ticketComments"); tracker(value.parent, "charter.parent", "open"); string(value.parentBody, "charter.parentBody"); strings(value.parentComments, "charter.parentComments"); assert(value.ticket.number !== value.parent.number, "ticket and parent must differ"); string(value.userVisibleOutcome, "charter.userVisibleOutcome");
  array(value.criteria, "charter.criteria", true); const criterionIds = [];
  value.criteria.forEach((item, index) => { object(item, `charter.criteria[${index}]`); exact(item, ["criterionId", "text"], `charter.criteria[${index}]`); string(item.criterionId, `charter.criteria[${index}].criterionId`); string(item.text, `charter.criteria[${index}].text`); assert(!criterionIds.includes(item.criterionId), `duplicate criterion: ${item.criterionId}`); criterionIds.push(item.criterionId); });
  array(value.testSeams, "charter.testSeams", true); const seamIds = [];
  value.testSeams.forEach((item, index) => { object(item, `charter.testSeams[${index}]`); exact(item, ["seamId", "criterionIds", "kind", "description"], `charter.testSeams[${index}]`); string(item.seamId, `charter.testSeams[${index}].seamId`); assert(!seamIds.includes(item.seamId), `duplicate seam: ${item.seamId}`); seamIds.push(item.seamId); strings(item.criterionIds, `charter.testSeams[${index}].criterionIds`, true); item.criterionIds.forEach((id) => assert(criterionIds.includes(id), `unknown seam criterion: ${id}`)); oneOf(item.kind, ["package-interface", "cli", "integration", "tui"], `charter.testSeams[${index}].kind`); string(item.description, `charter.testSeams[${index}].description`); });
  criterionIds.forEach((id) => assert(value.testSeams.some((seam) => seam.criterionIds.includes(id)), `criterion has no test seam: ${id}`));
  array(value.mechanicalChecks, "charter.mechanicalChecks", true); const checkIds = [];
  value.mechanicalChecks.forEach((item, index) => { object(item, `charter.mechanicalChecks[${index}]`); exact(item, ["checkId", "command", "required"], `charter.mechanicalChecks[${index}]`); string(item.checkId, `charter.mechanicalChecks[${index}].checkId`); assert(!checkIds.includes(item.checkId), `duplicate mechanical check: ${item.checkId}`); checkIds.push(item.checkId); string(item.command, `charter.mechanicalChecks[${index}].command`); boolean(item.required, `charter.mechanicalChecks[${index}].required`, true); });
  strings(value.mutablePaths, "charter.mutablePaths", true); value.mutablePaths.forEach((path, index) => repositoryPath(path, `charter.mutablePaths[${index}]`)); strings(value.safety, "charter.safety", true); strings(value.outOfScope, "charter.outOfScope"); array(value.startingWorktree, "charter.startingWorktree"); value.startingWorktree.forEach((line) => assert(typeof line === "string", "startingWorktree lines must be strings")); strings(value.userOwnedPaths, "charter.userOwnedPaths"); value.userOwnedPaths.forEach((path, index) => repositoryPath(path, `charter.userOwnedPaths[${index}]`));
}

export function validateEvent(event, { fragment = false } = {}) {
  object(event, "event"); assert(event.v === 1, "event.v must be 1"); string(event.type, "event.type"); assert(TYPES.has(event.type), `unknown event type: ${event.type}`); oneOf(event.actor, ACTORS, `${event.type}.actor`);
  if (fragment) assert(event.seq === undefined, "fragment events must omit seq"); else integer(event.seq, `${event.type}.seq`);
  const base = ["v", "type", "actor", ...(fragment ? [] : ["seq"])]; const keys = (...fields) => exact(event, [...base, ...fields], event.type); const attempt = () => integer(event.attempt, `${event.type}.attempt`); const actor = (...roles) => oneOf(event.actor, roles, `${event.type}.actor`);
  switch (event.type) {
    case "run.started": keys("runId", "charter", "evidence"); actor("parent"); string(event.runId, "run.started.runId"); assert(/^[a-zA-Z0-9._-]+$/.test(event.runId), "runId must be filename-safe"); validateCharter(event.charter); evidence(event.evidence, "run.started.evidence"); break;
    case "ticket.started": keys("blockers", "frontierStatus", "evidence"); actor("parent"); array(event.blockers, "ticket.started.blockers"); event.blockers.forEach((item, index) => tracker(item, `ticket.started.blockers[${index}]`, "closed")); assert(event.frontierStatus === "ready", "frontierStatus must be ready"); evidence(event.evidence, "ticket.started.evidence"); break;
    case "attempt.started": keys("attempt", "kind", "agentId", "authorizedFailureIds", "direction"); actor("parent"); attempt(); oneOf(event.kind, ["initial", "repair", "revision", "retest"], "attempt.started.kind"); string(event.agentId, "attempt.started.agentId"); strings(event.authorizedFailureIds, "attempt.started.authorizedFailureIds"); event.authorizedFailureIds.forEach((id) => failureId(id, "authorizedFailureIds")); string(event.direction, "attempt.started.direction", true); break;
    case "implementation.applied": keys("attempt", "agentId", "mode", "failureIds", "files", "tests", "summary", "residualRisk", "evidence"); actor("builder", "repairer", "parent"); attempt(); string(event.agentId, "implementation.applied.agentId"); oneOf(event.mode, ["changed", "unchanged", "blocked"], "implementation.applied.mode"); strings(event.failureIds, "implementation.applied.failureIds"); event.failureIds.forEach((id) => failureId(id, "implementation.applied.failureIds")); strings(event.files, "implementation.applied.files"); strings(event.tests, "implementation.applied.tests"); string(event.summary, "implementation.applied.summary"); string(event.residualRisk, "implementation.applied.residualRisk"); evidence(event.evidence, "implementation.applied.evidence"); break;
    case "mechanical.verification.recorded": keys("attempt", "checks", "scopeAudit", "ticketFiles", "worktreeStatus", "evidence"); actor("parent"); attempt(); array(event.checks, "mechanical.checks", true); event.checks.forEach((check, index) => { object(check, `checks[${index}]`); exact(check, ["checkId", "command", "status", "exitCode", "evidence"], `checks[${index}]`); string(check.checkId, `checks[${index}].checkId`); string(check.command, `checks[${index}].command`); oneOf(check.status, ["passed", "failed", "blocked"], `checks[${index}].status`); assert(check.exitCode === null || Number.isInteger(check.exitCode), `checks[${index}].exitCode must be an integer or null`); assert(check.status === "blocked" ? check.exitCode === null : check.status === "passed" ? check.exitCode === 0 : Number.isInteger(check.exitCode) && check.exitCode !== 0, `checks[${index}].exitCode does not match status`); evidence(check.evidence, `checks[${index}].evidence`); }); oneOf(event.scopeAudit, ["clean", "failed", "blocked"], "mechanical.scopeAudit"); strings(event.ticketFiles, "mechanical.ticketFiles"); event.ticketFiles.forEach((path, index) => repositoryPath(path, `mechanical.ticketFiles[${index}]`)); array(event.worktreeStatus, "mechanical.worktreeStatus"); event.worktreeStatus.forEach((line) => assert(typeof line === "string", "worktreeStatus lines must be strings")); evidence(event.evidence, "mechanical.evidence"); break;
    case "acceptance.started": keys("attempt", "verifierId", "evidence"); actor("parent"); attempt(); string(event.verifierId, "acceptance.started.verifierId"); evidence(event.evidence, "acceptance.started.evidence"); break;
    case "criterion.checked": keys("attempt", "verifierId", "criterionId", "seamId", "status", "notes", "evidence"); actor("acceptance-verifier"); attempt(); for (const field of ["verifierId", "criterionId", "seamId", "notes"]) string(event[field], `criterion.checked.${field}`); oneOf(event.status, ["pass", "fail", "blocked"], "criterion.checked.status"); evidence(event.evidence, "criterion.checked.evidence"); break;
    case "acceptance.closed": keys("attempt", "verifierId", "evidence"); actor("acceptance-verifier"); attempt(); string(event.verifierId, "acceptance.closed.verifierId"); evidence(event.evidence, "acceptance.closed.evidence"); break;
    case "failure.raised": keys("attempt", "verifierId", "failureId", "sourceKind", "sourceId", "classification", "summary", "actual", "expected", "evidence"); actor("parent", "acceptance-verifier"); attempt(); string(event.verifierId, "failure.raised.verifierId"); failureId(event.failureId, "failure.raised.failureId"); oneOf(event.sourceKind, ["agent", "mechanical", "criterion"], "failure.raised.sourceKind"); for (const field of ["sourceId", "summary", "actual", "expected"]) string(event[field], `failure.raised.${field}`); oneOf(event.classification, ["repairable", "decision-required", "scope-expansion", "external"], "failure.raised.classification"); evidence(event.evidence, "failure.raised.evidence"); break;
    case "repair.applied": keys("attempt", "agentId", "failureId", "files", "tests", "summary", "residualRisk", "evidence"); actor("repairer"); attempt(); string(event.agentId, "repair.applied.agentId"); failureId(event.failureId, "repair.applied.failureId"); strings(event.files, "repair.applied.files", true); strings(event.tests, "repair.applied.tests", true); string(event.summary, "repair.applied.summary"); string(event.residualRisk, "repair.applied.residualRisk"); evidence(event.evidence, "repair.applied.evidence"); break;
    case "failure.verification.recorded": keys("attempt", "verifierId", "failureId", "status", "notes", "evidence"); actor("parent", "acceptance-verifier"); attempt(); string(event.verifierId, "failure.verification.verifierId"); failureId(event.failureId, "failure.verification.failureId"); oneOf(event.status, ["passed", "failed", "blocked"], "failure.verification.status"); string(event.notes, "failure.verification.notes"); evidence(event.evidence, "failure.verification.evidence"); break;
    case "attempt.closed": keys("attempt", "outcome", "openFailureIds", "residualRisk", "evidence"); actor("parent"); attempt(); oneOf(event.outcome, ["ready", "failed", "blocked"], "attempt.closed.outcome"); strings(event.openFailureIds, "attempt.closed.openFailureIds"); event.openFailureIds.forEach((id) => failureId(id, "attempt.closed.openFailureIds")); string(event.residualRisk, "attempt.closed.residualRisk"); evidence(event.evidence, "attempt.closed.evidence"); break;
    case "human.decided": keys("attempt", "action", "direction", "evidence"); actor("parent"); attempt(); oneOf(event.action, ["accept", "revise", "retest", "stop"], "human.decided.action"); string(event.direction, "human.decided.direction", true); assert(event.action === "revise" ? event.direction.trim() : !event.direction, "direction is required only for revise"); evidence(event.evidence, "human.decided.evidence"); break;
    case "run.blocked": keys("attempt", "stage", "failureIds", "reason", "requiredAction", "evidence"); actor("parent"); attempt(); oneOf(event.stage, ["attempt", "commit", "tracker"], "run.blocked.stage"); strings(event.failureIds, "run.blocked.failureIds"); event.failureIds.forEach((id) => failureId(id, "run.blocked.failureIds")); string(event.reason, "run.blocked.reason"); string(event.requiredAction, "run.blocked.requiredAction"); evidence(event.evidence, "run.blocked.evidence"); break;
    case "run.resumed": keys("attempt", "stage", "failureIds", "resolution", "evidence"); actor("parent"); attempt(); oneOf(event.stage, ["attempt", "commit", "tracker"], "run.resumed.stage"); strings(event.failureIds, "run.resumed.failureIds"); event.failureIds.forEach((id) => failureId(id, "run.resumed.failureIds")); string(event.resolution, "run.resumed.resolution"); evidence(event.evidence, "run.resumed.evidence"); break;
    case "commit.recorded": keys("attempt", "status", "sha", "files", "worktreeStatus", "evidence"); actor("parent"); attempt(); oneOf(event.status, ["succeeded", "failed", "blocked"], "commit.recorded.status"); string(event.sha, "commit.recorded.sha", true); assert(event.status === "succeeded" ? event.sha.trim() : !event.sha, "commit sha is required only on success"); strings(event.files, "commit.recorded.files"); array(event.worktreeStatus, "commit.recorded.worktreeStatus"); event.worktreeStatus.forEach((line) => assert(typeof line === "string", "commit worktreeStatus lines must be strings")); evidence(event.evidence, "commit.recorded.evidence"); break;
    case "tracker.recorded": keys("attempt", "status", "ticket", "parent", "parentModified", "evidence"); actor("parent"); attempt(); oneOf(event.status, ["succeeded", "failed", "blocked"], "tracker.recorded.status"); tracker(event.ticket, "tracker.recorded.ticket"); tracker(event.parent, "tracker.recorded.parent", "open"); boolean(event.parentModified, "tracker.recorded.parentModified", false); evidence(event.evidence, "tracker.recorded.evidence"); break;
    case "ticket.closed": keys("attempt", "commitSha", "finalWorktree", "residualRisk", "evidence"); actor("parent"); attempt(); string(event.commitSha, "ticket.closed.commitSha"); array(event.finalWorktree, "ticket.closed.finalWorktree"); event.finalWorktree.forEach((line) => assert(typeof line === "string", "finalWorktree lines must be strings")); string(event.residualRisk, "ticket.closed.residualRisk"); evidence(event.evidence, "ticket.closed.evidence"); break;
    case "run.closed": keys("reason", "ticketState", "parentState", "parentModified", "commitSha", "finalWorktree", "residualRisk", "evidence"); actor("parent"); oneOf(event.reason, ["ticket-closed", "stopped"], "run.closed.reason"); oneOf(event.ticketState, ["open", "closed"], "run.closed.ticketState"); assert(event.parentState === "open", "run.closed.parentState must remain open"); boolean(event.parentModified, "run.closed.parentModified", false); string(event.commitSha, "run.closed.commitSha", true); array(event.finalWorktree, "run.closed.finalWorktree"); event.finalWorktree.forEach((line) => assert(typeof line === "string", "finalWorktree lines must be strings")); string(event.residualRisk, "run.closed.residualRisk"); evidence(event.evidence, "run.closed.evidence"); break;
  }
}

export function reduce(events) {
  assert(events.length, "ledger is empty");
  const state = { run: null, ticket: null, attempts: new Map(), failures: new Map(), decisions: [], consumedDecisions: new Set(), stopping: false, blocked: null, blockers: [], awaitingBlock: null, resumed: null, resumes: [], commit: null, commits: [], tracker: null, trackers: [], ticketClosed: null, closed: null, agentIds: new Set() };
  let active = null;
  for (let index = 0; index < events.length; index++) {
    const event = events[index]; validateEvent(event); assert(event.seq === index + 1, `event seq must be contiguous at ${index + 1}`); assert(!state.closed, `event ${event.seq} occurs after run.closed`);
    if (!state.run && event.type !== "run.started") throw new Error("run.started must be first");
    if (state.stopping && event.type !== "run.closed") throw new Error("human stop must be followed immediately by run.closed");
    if (state.awaitingBlock && event.type !== "run.blocked") throw new Error(`${state.awaitingBlock.stage} failure must be followed by run.blocked`);
    if (state.blocked && !["run.resumed", "human.decided", "run.closed"].includes(event.type)) throw new Error("run is blocked and must resume or stop before continuing");
    switch (event.type) {
      case "run.started": assert(index === 0 && !state.run, "run.started must be first and unique"); state.run = event; break;
      case "ticket.started": assert(index === 1 && !state.ticket, "ticket.started must be second and unique"); assert(event.blockers.every((blocker) => blocker.state === "closed"), "all blockers must be closed"); state.ticket = event; break;
      case "attempt.started": {
        assert(state.ticket, "ticket must start before attempts"); assert(!active, "attempts cannot overlap"); assert(event.attempt === state.attempts.size + 1, "attempt numbers must be contiguous"); assert(!state.agentIds.has(event.agentId), `agentId must be fresh: ${event.agentId}`); state.agentIds.add(event.agentId);
        const prior = [...state.attempts.values()].at(-1), decision = state.decisions.at(-1);
        if (event.kind === "initial") assert(event.attempt === 1 && !event.authorizedFailureIds.length && !event.direction, "initial attempt must be first and unqualified");
        if (event.kind === "repair") { assert(prior?.closed?.outcome === "failed" || state.resumed?.stage === "attempt", "repair requires a failed or resumed blocked attempt"); const open = [...state.failures].filter(([, value]) => !["fixed", "resolved-awaiting-verification"].includes(value.status)).map(([id, value]) => { assert(value.event.classification === "repairable", `failure is not automatically repairable: ${id}`); return id; }); assert(open.length && sameSet(event.authorizedFailureIds, open), "repair must authorize every open repairable failure"); assert(!event.direction, "repair direction must be empty"); }
        if (event.kind === "revision") { assert(decision?.action === "revise" && decision.attempt === prior?.event.attempt && !state.consumedDecisions.has(decision), "revision requires the immediately preceding unconsumed revise decision"); assert(event.direction === decision.direction && !event.authorizedFailureIds.length, "revision must carry the human direction only"); state.consumedDecisions.add(decision); }
        if (event.kind === "retest") { const decided = decision?.action === "retest" && decision.attempt === prior?.event.attempt && !state.consumedDecisions.has(decision); assert(decided || state.resumed?.stage === "attempt", "retest requires the immediately preceding unconsumed retest decision or resumed attempt blocker"); if (decided) state.consumedDecisions.add(decision); assert(!event.authorizedFailureIds.length && !event.direction, "retest cannot authorize changes"); }
        const resumedFailureIds = state.resumed?.stage === "attempt" ? [...state.resumed.failureIds] : []; state.resumed = null; active = { event, resumedFailureIds, implementation: null, mechanical: null, acceptance: null, criteria: new Map(), acceptanceClosed: null, repairs: new Set(), repairEvents: [], verifications: new Map(), failuresRaised: [], closed: null }; state.attempts.set(event.attempt, active); break;
      }
      case "implementation.applied": {
        assert(active?.event.attempt === event.attempt && !active.implementation, "implementation must occur once in the active attempt"); assert(event.agentId === active.event.agentId, "implementation agent must match attempt agent");
        const expectedActor = active.event.kind === "repair" ? "repairer" : active.event.kind === "retest" ? "parent" : "builder"; assert(event.actor === expectedActor, `implementation actor must be ${expectedActor}`);
        if (active.event.kind === "retest") assert(event.mode === "unchanged" && !event.files.length && !event.tests.length, "retest implementation must be unchanged"); else assert(["changed", "blocked"].includes(event.mode), "build and repair attempts must record changed or blocked implementation");
        if (event.mode === "blocked") assert(!event.files.length && !event.tests.length, "blocked implementation cannot claim file or test changes"); assert(sameSet(event.failureIds, active.event.authorizedFailureIds), "implementation failure IDs must match attempt authorization"); assertTicketPaths(event.files, state.run.charter, "implementation file"); active.implementation = event; break;
      }
      case "repair.applied": assert(active?.event.attempt === event.attempt && active.event.kind === "repair" && active.implementation?.mode === "changed", "repair must follow changed implementation in an active repair attempt"); assert(event.agentId === active.event.agentId, "repair agent must match attempt agent"); assert(active.event.authorizedFailureIds.includes(event.failureId), `repair is not authorized: ${event.failureId}`); assert(!active.repairs.has(event.failureId), `duplicate repair: ${event.failureId}`); assertTicketPaths(event.files, state.run.charter, "repair file"); active.repairs.add(event.failureId); active.repairEvents.push(event); break;
      case "mechanical.verification.recorded": {
        assert(active?.event.attempt === event.attempt && active.implementation?.mode !== "blocked" && !active.mechanical, "mechanical verification must follow a non-blocked implementation once"); const expected = state.run.charter.mechanicalChecks; assert(event.checks.length === expected.length, "every mechanical check must be recorded exactly once");
        for (const check of expected) { const matches = event.checks.filter((item) => item.checkId === check.checkId); assert(matches.length === 1, `mechanical check must occur once: ${check.checkId}`); assert(matches[0].command === check.command, `mechanical command changed: ${check.checkId}`); }
        assertTicketPaths(event.ticketFiles, state.run.charter, "mechanical ticket file"); if (event.scopeAudit === "clean") assert(event.ticketFiles.length > 0, "clean scope audit requires a non-empty ticket delta"); active.mechanical = event; break;
      }
      case "acceptance.started": assert(active?.event.attempt === event.attempt && active.mechanical && !active.acceptance, "acceptance must follow mechanical verification once"); assert(active.mechanical.scopeAudit === "clean" && active.mechanical.checks.every((check) => check.status === "passed"), "acceptance requires passing mechanical verification"); assert(!state.agentIds.has(event.verifierId), `verifierId must be fresh: ${event.verifierId}`); state.agentIds.add(event.verifierId); active.acceptance = event; break;
      case "criterion.checked": assert(active?.event.attempt === event.attempt && active.acceptance && !active.acceptanceClosed, "criteria require active acceptance"); assert(!active.failuresRaised.length && !active.verifications.size, "all criteria must precede acceptance failure and verification events"); assert(event.verifierId === active.acceptance.verifierId, "criterion verifier must match acceptance"); assert(!active.criteria.has(event.criterionId), `duplicate criterion in attempt: ${event.criterionId}`); assert(state.run.charter.criteria.some((criterion) => criterion.criterionId === event.criterionId), `unknown criterion: ${event.criterionId}`); { const seam = state.run.charter.testSeams.find((item) => item.seamId === event.seamId); assert(seam?.criterionIds.includes(event.criterionId), `seam does not cover criterion: ${event.criterionId}`); } active.criteria.set(event.criterionId, event); break;
      case "acceptance.closed": {
        assert(active?.event.attempt === event.attempt && active.acceptance && !active.acceptanceClosed, "acceptance must be active and close once"); assert(event.verifierId === active.acceptance.verifierId, "acceptance closer must be the verifier"); assert(sameSet([...active.criteria.keys()], state.run.charter.criteria.map((item) => item.criterionId)), "acceptance must account for every criterion exactly once");
        for (const criterion of active.criteria.values()) if (criterion.status !== "pass") assert([...active.failuresRaised, ...active.verifications.keys()].some((id) => { const failure = state.failures.get(id)?.event; return failure?.sourceKind === "criterion" && failure.sourceId === criterion.criterionId; }), `acceptance closure requires failure accounting for criterion: ${criterion.criterionId}`);
        const expectedVerifications = [...active.event.authorizedFailureIds, ...active.resumedFailureIds]; assert(sameSet([...active.verifications.keys()], expectedVerifications), "acceptance closure requires complete failure verification accounting"); active.acceptanceClosed = event; break;
      }
      case "failure.raised": {
        assert(active?.event.attempt === event.attempt, "failure must belong to active attempt");
        if (event.actor === "acceptance-verifier") { assert(active.acceptance && !active.acceptanceClosed, "verifier failure events must precede acceptance.closed"); assert(!active.verifications.size, "acceptance failures must precede failure verification events"); }
        if (event.sourceKind === "criterion") { assert(event.actor === "acceptance-verifier", "criterion failures must be acceptance-verifier authored"); assert(active.acceptance && event.verifierId === active.acceptance.verifierId, "criterion failure must be authored by the active verifier"); const source = active.criteria.get(event.sourceId); assert(source?.status !== "pass", `criterion failure source must fail or block: ${event.sourceId}`); if (source.status === "blocked") assert(event.classification !== "repairable", "blocked criterion failure cannot be automatically repairable"); }
        else if (event.sourceKind === "agent") { assert(event.actor === "parent" && event.verifierId === "parent", "agent blockers must be parent audited"); assert(active.implementation?.mode === "blocked" && event.sourceId === active.event.agentId, "agent blocker must identify the active blocked agent"); assert(event.classification !== "repairable", "agent blocker cannot be automatically repairable"); }
        else { assert(event.actor === "parent" && event.verifierId === "parent", "mechanical failures must be parent authored"); const status = event.sourceId === "scope-audit" ? active.mechanical?.scopeAudit : active.mechanical?.checks.find((check) => check.checkId === event.sourceId)?.status; assert(status && !["clean", "passed"].includes(status), `mechanical failure source must identify a non-pass check or scope-audit: ${event.sourceId}`); if (status === "blocked") assert(event.classification !== "repairable", "blocked mechanical failure cannot be automatically repairable"); }
        const sourceOwner = [...state.failures.entries()].find(([, item]) => item.event.sourceKind === event.sourceKind && item.event.sourceId === event.sourceId); if (sourceOwner) assert(sourceOwner[0] === event.failureId, `failure source already owns stable identity ${sourceOwner[0]}`);
        const existing = state.failures.get(event.failureId);
        if (existing) { assert(["fixed", "resolved-awaiting-verification"].includes(existing.status), `failure is already open: ${event.failureId}`); assert(existing.event.sourceKind === event.sourceKind && existing.event.sourceId === event.sourceId && existing.event.classification === event.classification && existing.event.expected === event.expected, `reused failure identity changed: ${event.failureId}`); existing.event = event; existing.history.push(event); existing.status = "open"; }
        else { assert(event.failureId === `BF-${String(state.failures.size + 1).padStart(3, "0")}`, `next failure ID must be BF-${String(state.failures.size + 1).padStart(3, "0")}`); state.failures.set(event.failureId, { event, history: [event], status: "open" }); }
        assert(!active.failuresRaised.includes(event.failureId), `failure already raised in attempt: ${event.failureId}`); active.failuresRaised.push(event.failureId); break;
      }
      case "failure.verification.recorded": { assert(active?.event.attempt === event.attempt && active.mechanical, "failure verification requires fresh post-mechanical evidence"); assert(!active.acceptanceClosed, "failure verification must precede acceptance.closed"); if (active.acceptance) assert(sameSet([...active.criteria.keys()], state.run.charter.criteria.map((item) => item.criterionId)), "all criteria must precede failure verification events"); const repaired = active.event.authorizedFailureIds.includes(event.failureId), resumed = active.resumedFailureIds.includes(event.failureId); assert(repaired || resumed, `failure verification is not authorized: ${event.failureId}`); assert(!active.verifications.has(event.failureId), `duplicate failure verification: ${event.failureId}`); const failure = state.failures.get(event.failureId); assert(failure, `unknown failure: ${event.failureId}`); if (repaired) assert(active.repairs.has(event.failureId), `failure has no repair in this attempt: ${event.failureId}`); if (failure.event.sourceKind === "agent") { assert(event.actor === "acceptance-verifier" && active.acceptance && event.verifierId === active.acceptance.verifierId && sameSet([...active.criteria.keys()], state.run.charter.criteria.map((item) => item.criterionId)) && [...active.criteria.values()].every((item) => item.status === "pass"), "resumed agent blocker requires complete passing fresh acceptance"); }
        else if (event.actor === "acceptance-verifier") { assert(active.acceptance && event.verifierId === active.acceptance.verifierId, "failure verification must use the active fresh verifier"); const sourceStatus = active.criteria.get(failure.event.sourceId)?.status, expectedStatus = event.status === "passed" ? "pass" : event.status === "failed" ? "fail" : "blocked"; assert(failure.event.sourceKind === "criterion" && sourceStatus === expectedStatus, `criterion repair verification ${event.status} requires ${expectedStatus} criterion evidence`); }
        else { assert(event.verifierId === "parent" && failure.event.sourceKind === "mechanical", "parent verification is limited to mechanical failures"); const sourceStatus = failure.event.sourceId === "scope-audit" ? active.mechanical.scopeAudit : active.mechanical.checks.find((check) => check.checkId === failure.event.sourceId)?.status, expectedStatus = event.status === "passed" ? failure.event.sourceId === "scope-audit" ? "clean" : "passed" : event.status; assert(sourceStatus === expectedStatus, `mechanical repair verification ${event.status} requires matching source evidence`); }
        failure.status = event.status === "passed" ? "fixed" : event.status; active.verifications.set(event.failureId, event); break; }
      case "attempt.closed": {
        assert(active?.event.attempt === event.attempt && !active.closed && active.implementation, "active attempted implementation must close once");
        if (active.implementation.mode === "blocked") { const agentFailures = active.failuresRaised.filter((id) => state.failures.get(id).event.sourceKind === "agent"); assert(agentFailures.length === 1, "blocked implementation requires exactly one agent blocker"); const open = [...state.failures].filter(([, value]) => value.status !== "fixed").map(([id]) => id).sort(); assert(event.outcome === "blocked", "blocked implementation outcome must be blocked"); assert(sameSet(event.openFailureIds, open), "attempt open failures must match reducer state"); const blockers = open.filter((id) => state.failures.get(id).event.classification !== "repairable"); state.awaitingBlock = { stage: "attempt", failureIds: blockers, attempt: event.attempt }; active.closed = event; active = null; break; }
        assert(active.mechanical, "non-blocked attempt requires mechanical verification"); const mechanicalBlocked = active.mechanical.scopeAudit === "blocked" || active.mechanical.checks.some((check) => check.status === "blocked"); const mechanicalFailed = active.mechanical.scopeAudit === "failed" || active.mechanical.checks.some((check) => check.status === "failed");
        if (!mechanicalBlocked && !mechanicalFailed) assert(active.acceptanceClosed, "passing mechanical verification requires complete acceptance");
        const criterionBlocked = [...active.criteria.values()].some((item) => item.status === "blocked"), criterionFailed = [...active.criteria.values()].some((item) => item.status === "fail");
        const covered = (kind, source) => [...state.failures.values()].some((item) => item.status !== "fixed" && item.event.sourceKind === kind && item.event.sourceId === source);
        const nonpassSources = [...active.criteria.values()].filter((item) => item.status !== "pass").map((item) => item.criterionId); for (const source of nonpassSources) assert(covered("criterion", source), `non-pass criterion requires a matching failure: ${source}`);
        const mechanicalSources = [...active.mechanical.checks.filter((check) => check.status !== "passed").map((check) => check.checkId), ...(active.mechanical.scopeAudit === "clean" ? [] : ["scope-audit"])]; for (const source of mechanicalSources) assert(covered("mechanical", source), `non-pass mechanical source requires a matching failure: ${source}`);
        if (active.event.kind === "repair") assert(sameSet([...active.repairs], active.event.authorizedFailureIds), "every authorized failure requires one repair"); const expectedVerifications = active.acceptanceClosed ? [...active.event.authorizedFailureIds, ...active.resumedFailureIds] : []; assert(sameSet([...active.verifications.keys()], expectedVerifications), "every repair or resumed blocker reaching acceptance requires independent verification");
        const open = [...state.failures].filter(([, value]) => value.status !== "fixed").map(([id]) => id).sort(); const blockedFailure = open.some((id) => ["external", "decision-required", "scope-expansion"].includes(state.failures.get(id).event.classification)); const expected = mechanicalBlocked || criterionBlocked || blockedFailure || [...active.verifications.values()].some((item) => item.status === "blocked") ? "blocked" : mechanicalFailed || criterionFailed || open.length || [...active.verifications.values()].some((item) => item.status === "failed") ? "failed" : "ready";
        assert(event.outcome === expected, `attempt outcome must be ${expected}`); assert(sameSet(event.openFailureIds, open), "attempt open failures must match reducer state"); active.closed = event; if (expected === "blocked") { const blockers = open.filter((id) => state.failures.get(id).event.classification !== "repairable" || state.failures.get(id).status === "blocked"); assert(blockers.length, "blocked attempt requires at least one blocker"); state.awaitingBlock = { stage: "attempt", failureIds: blockers, attempt: event.attempt }; } active = null; break;
      }
      case "human.decided": { const latest = [...state.attempts.values()].at(-1), prior = state.decisions.find((item) => item.attempt === event.attempt); assert(latest?.closed && latest.event.attempt === event.attempt, "decision requires latest closed attempt"); if (["accept", "retest"].includes(event.action)) assert(latest.closed.outcome === "ready", `${event.action} requires a ready attempt`); if (prior) assert(event.action === "stop" && prior.action === "accept" && ["commit", "tracker"].includes(state.blocked?.stage), "attempt already has a human decision"); state.decisions.push(event); if (event.action === "stop") state.stopping = true; break; }
      case "run.blocked": { assert(state.awaitingBlock && state.awaitingBlock.stage === event.stage && state.awaitingBlock.attempt === event.attempt, "run.blocked must match the pending failed stage"); assert(sameSet(event.failureIds, state.awaitingBlock.failureIds), "run.blocked failure IDs must match unresolved blockers"); state.awaitingBlock = null; state.blocked = event; state.blockers.push(event); break; }
      case "run.resumed": { assert(state.blocked && state.blocked.stage === event.stage, "resume must match active blocker"); assert(sameSet(event.failureIds, state.blocked.failureIds), "resume must account for every blocked failure"); const requiresDecision = event.failureIds.some((id) => ["decision-required", "scope-expansion"].includes(state.failures.get(id)?.event.classification)); if (requiresDecision) { const decision = state.decisions.at(-1); assert(decision?.action === "revise" && decision.attempt === event.attempt, "decision or scope blocker requires human revision direction"); } event.failureIds.forEach((id) => { const failure = state.failures.get(id); assert(failure && (failure.event.classification !== "repairable" || failure.status === "blocked"), `resumed failure must be an external, decision, scope, or verification blocker: ${id}`); failure.status = "resolved-awaiting-verification"; }); state.resumed = event; state.resumes.push(event); state.blocked = null; break; }
      case "commit.recorded": { const decision = state.decisions.at(-1), latest = [...state.attempts.values()].at(-1); assert(decision?.action === "accept" && decision.attempt === event.attempt && latest?.closed?.outcome === "ready" && latest.event.attempt === event.attempt, "commit requires acceptance of the latest ready attempt"); assert(!state.commit || state.commit.status !== "succeeded", "successful commit can be recorded only once"); assertTicketPaths(event.files, state.run.charter, "commit file"); if (event.status === "succeeded") { assert(/^(?:[a-f0-9]{40}|[a-f0-9]{64})$/.test(event.sha), "successful commit sha must be a full hexadecimal commit ID"); assert(event.files.length && sameSet(event.files, latest.mechanical.ticketFiles), "commit files must exactly match the accepted ticket delta"); } state.commit = event; state.commits.push(event); if (event.status !== "succeeded") state.awaitingBlock = { stage: "commit", failureIds: [], attempt: event.attempt }; break; }
      case "tracker.recorded": { assert(state.commit?.status === "succeeded" && state.commit.attempt === event.attempt, "tracker closure requires successful commit"); assert(!state.tracker || state.tracker.status !== "succeeded", "successful tracker closure can be recorded only once"); assert(sameTracker(event.ticket, state.run.charter.ticket) && sameTracker(event.parent, state.run.charter.parent), "tracker operation identities must match the charter"); if (event.status === "succeeded") assert(event.ticket.state === "closed", "successful tracker operation must close the active ticket"); state.tracker = event; state.trackers.push(event); if (event.status !== "succeeded") state.awaitingBlock = { stage: "tracker", failureIds: [], attempt: event.attempt }; break; }
      case "ticket.closed": assert(state.commit?.status === "succeeded" && state.tracker?.status === "succeeded", "ticket closure requires successful commit and tracker closure"); assert(event.commitSha === state.commit.sha, "ticket closure commit must match"); assert(!state.ticketClosed, "ticket can close only once"); state.ticketClosed = event; break;
      case "run.closed": if (event.reason === "ticket-closed") { assert(state.ticketClosed, "ticket-closed run requires ticket.closed"); assert(event.ticketState === "closed" && event.commitSha === state.commit.sha, "run closure must record closed ticket and commit"); } else { assert(state.decisions.at(-1)?.action === "stop", "stopped run requires human stop"); assert(!state.ticketClosed && event.ticketState === "open", "stopped run leaves ticket open"); } state.closed = event; break;
    }
  }
  assert(state.run, "missing run.started"); return state;
}

const cell = (value) => String(value).replaceAll("|", "\\|").replaceAll("\n", " ");
const evidenceText = (items) => items.map((item) => `${item.kind}:${item.ref}${item.sha256 ? `#${item.sha256.slice(0, 12)}` : ""}`).join(", ");
export function renderReport(events) {
  const state = reduce(events), charter = state.run.charter, lines = [
    `# Build Loop Report - ${state.run.runId}`, "", `**Ticket:** #${charter.ticket.number} - ${charter.ticket.title} (${charter.ticket.url})  `,
    `**Parent:** #${charter.parent.number} - ${charter.parent.title} (${charter.parent.url})  `, `**Outcome:** ${charter.userVisibleOutcome}`, "",
    "## Source contracts", "", "### Ticket body", "```markdown", charter.ticketBody, "```", "### Ticket comments", ...(charter.ticketComments.length ? charter.ticketComments.map((item) => `- ${item}`) : ["- None"]), "", "### Parent body", "```markdown", charter.parentBody, "```", "### Parent comments", ...(charter.parentComments.length ? charter.parentComments.map((item) => `- ${item}`) : ["- None"]), "",
    "## Charter", "", "### Acceptance criteria", ...charter.criteria.map((item) => `- **${item.criterionId}:** ${item.text}`), "",
    "### Test seams", ...charter.testSeams.map((item) => `- **${item.seamId}** (${item.kind}): ${item.description} [${item.criterionIds.join(", ")}]`), "",
    "### Mechanical checks", ...charter.mechanicalChecks.map((item) => `- **${item.checkId}:** \`${item.command}\``), "",
    "### Mutable scope", ...charter.mutablePaths.map((item) => `- ${item}`), "", "### User-owned paths", ...(charter.userOwnedPaths.length ? charter.userOwnedPaths.map((item) => `- ${item}`) : ["- None"]), "",
    "### Safety", ...charter.safety.map((item) => `- ${item}`), "", "### Out of scope", ...(charter.outOfScope.length ? charter.outOfScope.map((item) => `- ${item}`) : ["- None"]), "",
    "### Starting worktree", "```text", ...charter.startingWorktree, "```", `Evidence: ${evidenceText(state.run.evidence)}`, "",
    "## Dependency frontier", "", `Status: **${state.ticket.frontierStatus}**. Evidence: ${evidenceText(state.ticket.evidence)}`,
    ...(state.ticket.blockers.length ? state.ticket.blockers.map((item) => `- #${item.number} ${item.title}: ${item.state}`) : ["- No blockers"]), "",
    "## Attempts", "", "| Attempt | Kind | Agent | Outcome | Implementation |", "|---:|---|---|---|---|",
  ];
  for (const [number, attempt] of state.attempts) lines.push(`| ${number} | ${attempt.event.kind} | ${cell(attempt.event.agentId)} | ${attempt.closed?.outcome ?? "open"} | ${cell(attempt.implementation?.summary ?? "not recorded")} |`);
  for (const [number, attempt] of state.attempts) {
    lines.push("", `### Attempt ${number} evidence`, "", `- Implementation files: ${attempt.implementation?.files.join(", ") || "none"}`, `- Implementation tests: ${attempt.implementation?.tests.join(", ") || "none"}`, `- Implementation risk: ${attempt.implementation?.residualRisk ?? "not recorded"}`, `- Implementation evidence: ${attempt.implementation ? evidenceText(attempt.implementation.evidence) : "none"}`);
    if (attempt.mechanical) { lines.push(`- Scope audit: ${attempt.mechanical.scopeAudit}`, `- Ticket delta: ${attempt.mechanical.ticketFiles.join(", ")}`, `- Scope evidence: ${evidenceText(attempt.mechanical.evidence)}`); for (const check of attempt.mechanical.checks) lines.push(`- Check **${check.checkId}**: ${check.status} (exit ${check.exitCode ?? "blocked"}) - \`${check.command}\` - ${evidenceText(check.evidence)}`); }
    for (const repair of attempt.repairEvents) lines.push(`- Repair ${repair.failureId}: ${repair.summary}; files ${repair.files.join(", ")}; tests ${repair.tests.join(", ")}; risk ${repair.residualRisk}; evidence ${evidenceText(repair.evidence)}`);
    if (attempt.acceptanceClosed) lines.push(`- Acceptance closure evidence: ${evidenceText(attempt.acceptanceClosed.evidence)}`);
    for (const verification of attempt.verifications.values()) lines.push(`- Verification ${verification.failureId}: ${verification.status} by ${verification.verifierId}; ${verification.notes}; evidence ${evidenceText(verification.evidence)}`);
    if (attempt.closed) lines.push(`- Attempt residual risk: ${attempt.closed.residualRisk}; evidence ${evidenceText(attempt.closed.evidence)}`);
  }
  lines.push("", "## Criterion coverage", "", "| Attempt | Criterion | Seam | Status | Notes | Evidence |", "|---:|---|---|---|---|---|");
  for (const [number, attempt] of state.attempts) for (const item of attempt.criteria.values()) lines.push(`| ${number} | ${cell(item.criterionId)} | ${cell(item.seamId)} | ${item.status} | ${cell(item.notes)} | ${cell(evidenceText(item.evidence))} |`);
  if (![...state.attempts.values()].some((item) => item.criteria.size)) lines.push("| - | - | - | - | - | No acceptance review | ");
  lines.push("", "## Failures and repairs", "", "| ID | Source | Classification | Status | Actual / expected | Evidence |", "|---|---|---|---|---|---|");
  for (const [id, item] of state.failures) { lines.push(`| ${id} | ${item.event.sourceKind}:${cell(item.event.sourceId)} | ${item.event.classification} | ${item.status} | ${cell(item.event.actual)} / ${cell(item.event.expected)} | ${cell(evidenceText(item.event.evidence))} |`); if (item.history.length > 1) lines.push(`| ${id} history | ${item.history.length} occurrences | - | - | ${item.history.map((event) => `attempt ${event.attempt}: ${cell(event.actual)}`).join("; ")} | ${item.history.map((event) => cell(evidenceText(event.evidence))).join("; ")} |`); }
  if (!state.failures.size) lines.push("| - | - | - | - | No failures | - |");
  lines.push("", "## Blockers and resumptions", "", ...(state.blockers.length ? state.blockers.map((item) => `- Attempt ${item.attempt} ${item.stage} blocked: ${item.reason}. Required: ${item.requiredAction}. Failures: ${item.failureIds.join(", ") || "none"}. Evidence: ${evidenceText(item.evidence)}`) : ["- None."]), ...state.resumes.map((item) => `- Attempt ${item.attempt} ${item.stage} resumed: ${item.resolution}. Evidence: ${evidenceText(item.evidence)}`));
  lines.push("", "## Human decisions", "", ...(state.decisions.length ? state.decisions.map((item) => `- Attempt ${item.attempt}: **${item.action}**${item.direction ? ` - ${item.direction}` : ""}. Evidence: ${evidenceText(item.evidence)}`) : ["- None."]), "", "## Delivery operations", "");
  for (const item of state.commits) lines.push(`- Commit attempt ${item.attempt}: ${item.status}${item.sha ? ` ${item.sha}` : ""}; files ${item.files.join(", ") || "none"}; evidence ${evidenceText(item.evidence)}`);
  for (const item of state.trackers) lines.push(`- Tracker attempt ${item.attempt}: ${item.status}; ticket #${item.ticket.number} ${item.ticket.state}; parent #${item.parent.number} ${item.parent.state}, modified=${item.parentModified}; evidence ${evidenceText(item.evidence)}`);
  if (!state.commits.length && !state.trackers.length) lines.push("- None.");
  lines.push("", "## Closure", "", ...(state.ticketClosed ? [`Ticket closure: commit ${state.ticketClosed.commitSha}; residual risk ${state.ticketClosed.residualRisk}; evidence ${evidenceText(state.ticketClosed.evidence)}`] : []), state.closed ? `Run closed by **${state.closed.reason}**. Residual risk: ${state.closed.residualRisk}. Evidence: ${evidenceText(state.closed.evidence)}` : state.blocked ? `Run is blocked at **${state.blocked.stage}**: ${state.blocked.reason}` : "Run remains open.", "", "## Final worktree", "", "```text", ...(state.closed?.finalWorktree ?? state.commit?.worktreeStatus ?? []), "```", "");
  return lines.join("\n");
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  const cli = createLedgerCli({ name: "build-ledger", validateEvent, reduce, renderReport, refuseExisting: true });
  await executeLedgerCli(cli, process.argv.slice(2), "build-ledger");
}
