import { describe, expect, it } from "vitest";
import * as fs from "node:fs";
import * as path from "node:path";
import { classifyMachineEmittedLineShape } from "../../clients/generated-artifacts.js";
import { detectFileRole } from "../../clients/file-role.js";

describe("detectFileRole", () => {
	it("detects generated files from clawpatch-style filename patterns", () => {
		for (const filePath of [
			"proto/user.pb.go",
			"db/query_sqlc.go",
			"pkg/client_generated.go",
			"pkg/client_gen.go",
			"api/service_pb2.py",
			"api/service_pb2_grpc.py",
		]) {
			expect(detectFileRole(filePath)).toBe("generated");
		}
	});

	it("detects generated files from headers", () => {
		expect(
			detectFileRole(
				"src/client.ts",
				"// Code generated by tool. DO NOT EDIT.\nexport const x = 1;\n",
			),
		).toBe("generated");
	});

	// Refs #1152 (latent sibling of #1150/#1151): a Windows-shaped path must
	// classify coherently regardless of the running OS. Pre-fix,
	// `dirname(filePath)` used the module-default (POSIX on Linux); a
	// backslash-only Windows path has no `/` for POSIX `dirname` to find, so
	// it collapsed to `"."` and the `/tests/` dir-branch below never matched
	// — misclassifying a test file under `tests\` as "source" on Linux, even
	// though the byte-identical forward-slash form ("C:/proj/tests/foo.ts")
	// already classified correctly (POSIX `dirname` handles forward slashes
	// fine regardless of the leading drive letter). This test is meaningful
	// on BOTH OSes per the #1024 discipline: on native Windows it exercises
	// the (unchanged, already-correct) win32 `dirname`/`basename` path; on
	// Linux it exercises the new shape-committed `win32.dirname`/`basename`
	// branch that this fix adds — pre-fix, the backslash case below FAILED
	// on Linux (classified "source" instead of "test") while the
	// forward-slash case already passed.
	it("classifies a Windows-shaped path's test directory coherently across separator styles, even off native Windows", () => {
		for (const filePath of [
			"C:\\proj\\tests\\foo.ts",
			"C:/proj/tests/foo.ts",
			"C:\\proj\\src\\foo.test.ts",
			"\\\\server\\share\\tests\\foo.ts",
		]) {
			expect(detectFileRole(filePath)).toBe("test");
		}
	});

	it("still resolves index/init role for a Windows-shaped path (basename shape-coherence)", () => {
		expect(detectFileRole("C:\\proj\\src\\index.ts")).toBe("init");
	});

	it("does not misclassify a native POSIX path as Windows-shaped (no regression for the common case)", () => {
		expect(detectFileRole("/home/dev/project/tests/foo.ts")).toBe("test");
		expect(detectFileRole("/home/dev/project/src/foo.ts")).toBe("source");
	});

	// #2346 negative proof: the longest-line real file in `clients/` that
	// still classifies as plain SOURCE under the content-shape test. Measured
	// on 2026-08-28 with the shipped probe algorithm: the overall maximum mean
	// non-empty line length in `clients/` is 65.1 (`dispatch/runners/index.ts`,
	// which the role classifier reports as `init` for its basename), and of
	// the files that classify as `source`, the maximum is `clients/tool-event.ts`
	// at 52.1 — both far below the 2500 threshold. This test feeds the file's
	// REAL content so a threshold regression that starts capturing ordinary
	// source reds here.
	it("keeps the longest-line source-role file in clients/ as source (refs #2346)", () => {
		const longestLineFile = path.resolve(
			process.cwd(),
			"clients/tool-event.ts",
		);
		const content = fs.readFileSync(longestLineFile, "utf8");
		const measured = classifyMachineEmittedLineShape(content);
		expect(measured.generated).toBe(false);
		expect(measured.meanLineLength).toBeLessThan(200);
		expect(detectFileRole(longestLineFile, content)).toBe("source");
	});
});
