import test from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const packageDir = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = resolve(packageDir, "../..");
const syncScript = join(packageDir, "scripts", "sync-readme.mjs");
const packageReadme = join(packageDir, "README.md");

test("sync-readme resolves the repository README independently of cwd", () => {
  execFileSync(process.execPath, [syncScript], { cwd: tmpdir() });
  const generated = readFileSync(packageReadme, "utf8");
  const source = readFileSync(join(repoRoot, "README.md"), "utf8");
  const marker = 'Pi Guard operates only when `ctx.mode === "tui"`.';

  assert.match(generated, /^<!-- Generated from \.\.\/\.\.\/README\.md by scripts\/sync-readme\.mjs\. Do not edit this file directly\. -->/);
  assert.ok(source.includes(marker), "root README must contain the Pi Guard marker");
  assert.ok(generated.includes(marker), "package README must be generated from this repository root");
});
