import { describe, expect, it } from "vitest";
import * as fs from "node:fs";
import * as path from "node:path";
import { classifyMachineEmittedLineShape } from "../../clients/generated-artifacts.js";
import { detectFileRole } from "../../clients/file-role.js";

describe("detectFileRole", () => {
	it("detects generated files from clawpatch-style filename patterns", () => {
		for (const filePath of [
			"proto/user.pb.go",
			"db/query_sqlc.go",
			"pkg/client_generated.go",
			"pkg/client_gen.go",
			"api/service_pb2.py",
			"api/service_pb2_grpc.py",
		]) {
			expect(detectFileRole(filePath)).toBe("generated");
		}
	});

	it("detects generated files from headers", () => {
		expect(
			detectFileRole(
				"src/client.ts",
				"// Code generated by tool. DO NOT EDIT.\nexport const x = 1;\n",
			),
		).toBe("generated");
	});

	// Refs #1152 (latent sibling of #1150/#1151): a Windows-shaped path must
	// classify coherently regardless of the running OS. Pre-fix,
	// `dirname(filePath)` used the module-default (POSIX on Linux); a
	// backslash-only Windows path has no `/` for POSIX `dirname` to find, so
	// it collapsed to `"."` and the `/tests/` dir-branch below never matched
	// — misclassifying a test file under `tests\` as "source" on Linux, even
	// though the byte-identical forward-slash form ("C:/proj/tests/foo.ts")
	// already classified correctly (POSIX `dirname` handles forward slashes
	// fine regardless of the leading drive letter). This test is meaningful
	// on BOTH OSes per the #1024 discipline: on native Windows it exercises
	// the (unchanged, already-correct) win32 `dirname`/`basename` path; on
	// Linux it exercises the new shape-committed `win32.dirname`/`basename`
	// branch that this fix adds — pre-fix, the backslash case below FAILED
	// on Linux (classified "source" instead of "test") while the
	// forward-slash case already passed.
	it("classifies a Windows-shaped path's test directory coherently across separator styles, even off native Windows", () => {
		for (const filePath of [
			"C:\\proj\\tests\\foo.ts",
			"C:/proj/tests/foo.ts",
			"C:\\proj\\src\\foo.test.ts",
			"\\\\server\\share\\tests\\foo.ts",
		]) {
			expect(detectFileRole(filePath)).toBe("test");
		}
	});

	it("still resolves index/init role for a Windows-shaped path (basename shape-coherence)", () => {
		expect(detectFileRole("C:\\proj\\src\\index.ts")).toBe("init");
	});

	it("does not misclassify a native POSIX path as Windows-shaped (no regression for the common case)", () => {
		expect(detectFileRole("/home/dev/project/tests/foo.ts")).toBe("test");
		expect(detectFileRole("/home/dev/project/src/foo.ts")).toBe("source");
	});

	// Refs #2880: hand-written pins for the test-file conventions the
	// test-runner client dispatches on. The table-derived rows are covered
	// by tests/clients/test-file-classifier-parity.test.ts, which imports
	// and iterates the REAL SOURCE_TO_TEST_PATTERNS table (#2928 fold);
	// this hand-written set remains for the conventions BEYOND the table
	// (`*Test.java`, `*Test.kt`, `*Tests.cs`, `_spec.rb` — runners whose
	// discovery rows the table does not carry). A convention
	// missing here lets an edited test file take the related-discovery
	// path and run the wrong tests or none. Each row pairs the convention with a co-located
	// source file the same convention must NOT claim, so a row proves its
	// own name rule rather than a test-directory rule. The `_test.go` row
	// is the reported defect: pre-fix it classified as "source" and
	// `getTestRunTarget` for the edited file returned null.
	it("recognises every test-file convention the test-runner client dispatches on", () => {
		const cases: Array<[string, "test" | "source"]> = [
			// Go `*_test.go` suffix (the #2880 row).
			["/repo/pkg/foo_test.go", "test"],
			["/repo/pkg/foo.go", "source"],
			// pytest knows BOTH `test_*.py` and `*_test.py`.
			["/repo/pkg/test_foo.py", "test"],
			["/repo/pkg/foo_test.py", "test"],
			["/repo/pkg/foo.py", "source"],
			// RSpec `*_spec.rb` suffix, outside any spec/ directory.
			["/repo/pkg/thing_spec.rb", "test"],
			["/repo/pkg/thing.rb", "source"],
			// ExUnit `*_test.exs` suffix, outside the test/ tree.
			["/repo/lib/accounts/user_test.exs", "test"],
			["/repo/lib/accounts/user.ex", "source"],
			// JUnit/Surefire/Gradle `*Test.java` suffix, outside src/test/.
			["/repo/src/main/java/com/x/FooTest.java", "test"],
			["/repo/src/main/java/com/x/Foo.java", "source"],
			// Kotlin `*Test.kt` suffix.
			["/repo/src/FooTest.kt", "test"],
			["/repo/src/Foo.kt", "source"],
			// dotnet `*Tests.cs` suffix.
			["/repo/src/FooTests.cs", "test"],
			["/repo/src/Foo.cs", "source"],
			// PHPUnit `*Test.php` suffix.
			["/repo/src/ThingTest.php", "test"],
			["/repo/src/Thing.php", "source"],
			// JS/TS `.test.`/`.spec.` infixes (pre-existing behavior, pinned).
			["/repo/src/foo.test.ts", "test"],
			["/repo/src/foo.spec.js", "test"],
			// minitest `test_*.rb` prefix (pre-existing behavior, pinned).
			["/repo/test/test_foo.rb", "test"],
			// Anchor precision: the `_test.`/`_spec.` infixes need the
			// underscore, and the CamelCase suffix needs the capital T, so
			// ordinary words containing "test"/"spec" stay source.
			["/repo/pkg/contest.py", "source"],
			["/repo/src/latest.ts", "source"],
			["/repo/src/main/java/com/x/contest.java", "source"],
		];
		for (const [file, expected] of cases) {
			expect(detectFileRole(file), file).toBe(expected);
		}
	});

	// Refs #2928: `__tests__` is matched as a FULL path segment. The old
	// `dir.includes("/__tests__/")` arm could never see a file DIRECTLY under
	// `__tests__` — `dirname` yields no trailing slash — so
	// `/proj/__tests__/foo.ts` classified as "source" while every sibling
	// classifier (file-utils' substring arm, word-index's directory
	// alternation) said test. The fold makes `isTestFile` delegate to this
	// classifier, so the arm must cover every shape the old substring arm
	// did before the delegation can be behavior-preserving. Pre-fix, the
	// direct-child rows below FAILED (classified "source").
	it("classifies a file under a __tests__ directory as test on every path shape", () => {
		for (const filePath of [
			"/proj/__tests__/foo.ts",
			"/proj/__tests__/unit/foo.ts",
			"__tests__/foo.ts",
			"__tests__/unit/foo.ts",
			"C:\\proj\\__tests__\\foo.ts",
		]) {
			expect(detectFileRole(filePath), filePath).toBe("test");
		}
		// Anchor precision: the token inside a longer segment is not the
		// `__tests__` convention.
		expect(detectFileRole("/proj/x__tests__/foo.ts")).toBe("source");
		expect(detectFileRole("/proj/__tests__x/foo.ts")).toBe("source");
	});

	// #2346 negative proof: the longest-line real file in `clients/` that
	// still classifies as plain SOURCE under the content-shape test. Measured
	// on 2026-08-28 with the shipped probe algorithm: the overall maximum mean
	// non-empty line length in `clients/` is 65.1 (`dispatch/runners/index.ts`,
	// which the role classifier reports as `init` for its basename), and of
	// the files that classify as `source`, the maximum is `clients/tool-event.ts`
	// at 52.1 — both far below the 2500 threshold. This test feeds the file's
	// REAL content so a threshold regression that starts capturing ordinary
	// source reds here.
	it("keeps the longest-line source-role file in clients/ as source (refs #2346)", () => {
		const longestLineFile = path.resolve(
			process.cwd(),
			"clients/tool-event.ts",
		);
		const content = fs.readFileSync(longestLineFile, "utf8");
		const measured = classifyMachineEmittedLineShape(content);
		expect(measured.generated).toBe(false);
		expect(measured.meanLineLength).toBeLessThan(200);
		expect(detectFileRole(longestLineFile, content)).toBe("source");
	});
});
