// lane: windows-vitest — the case-variant cell below asserts the HOST
// filesystem's own case-folding answer, and only a real Windows (or APFS) host
// answers it `true`. The only boundary mocked is `safe-spawn`, a process
// boundary, so the lane needs no ruff binary.
/**
 * #3286 — `clients/ruff-client.ts` is the member of #3278's reported-path
 * identity family that lives OUTSIDE `clients/dispatch/runners/**`, which is
 * why #3284's grep and its absence detector both missed it. It answered "is
 * this reported finding about the file I ran for?" with
 * `path.resolve(item.filename) !== filterFile` — a bare `!==` (sub-shape A)
 * over a `path.resolve` with NO base, which silently means the EXTENSION's
 * `process.cwd()` rather than the directory ruff ran in (sub-shape B).
 *
 * Recurrence prevented, per direction:
 *
 * - DROPPED (#209 / #3277): a spelling that differs only in case is the SAME
 *   file on Windows and on a case-folding POSIX mount, so every fixable finding
 *   for the edited file was filtered out and the autofix reported `fixed: 0`.
 * - OVER-MERGED: a sibling Python file's fixable findings must not be counted
 *   as the edited file's own.
 *
 * Premise, established from upstream ruff at a pinned version rather than
 * assumed: the JSON renderer emits the `SourceFile`'s name VERBATIM —
 * `span.file().path(resolver)` (0.16.8
 * `crates/ruff_db/src/diagnostic/render/json.rs:58,120`) is `file.name()` for a
 * ruff diagnostic (`crates/ruff_db/src/diagnostic/mod.rs:1187-1193`), not the
 * cwd-relative `relative_path` the text renderers use (`mod.rs:1195-1204`) —
 * and that name is `SourceFileBuilder::new(path.to_string_lossy(), …)`
 * (`crates/ruff_linter/src/linter.rs:1049`) over a path the resolver has already
 * absolutized ("Normalize every path (e.g., convert from relative to
 * absolute)", `crates/ruff_workspace/src/resolver.rs:484`). ruff therefore
 * echoes the absolute path we hand it as argv: the BASE was already right, so
 * the case collision is NOT reachable under our own invocation today and these
 * cells say so — they are the predicate's two-directional contract pins, not a
 * defect repro, and they never feed a spelling ruff would not emit (#2432).
 */
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import type {
	SafeSpawnOptions,
	SpawnResult,
} from "../../clients/safe-spawn.js";

type SafeSpawnAsync = (
	command: string,
	args: string[],
	options?: SafeSpawnOptions,
) => Promise<SpawnResult>;

const spawned: Array<{ command: string; args: string[]; cwd?: string }> = [];

const { safeSpawnAsync } = vi.hoisted(() => ({
	safeSpawnAsync: vi.fn<SafeSpawnAsync>(),
}));

// The no-argument `importOriginal()` pass-through is the idiom
// `tests/config/vi-mock-export-sweep.test.ts` recognises as complete (#2784).
vi.mock("../../clients/safe-spawn.js", async (importOriginal) => ({
	...(await importOriginal()),
	safeSpawnAsync,
}));

/**
 * A real `ruff check --output-format json` payload, byte-identical to the
 * upstream snapshot it was taken from:
 *
 *   curl -s https://raw.githubusercontent.com/astral-sh/ruff/0.16.8/crates/ruff_db/src/diagnostic/render/snapshots/ruff_db__diagnostic__render__json__tests__output.snap \
 *     | diff - tests/fixtures/ruff-json/ruff-0.16.8-json-output.snap.txt
 *
 * Generated by UPSTREAM code, not by a transcription of it: that snapshot is
 * `env.render_diagnostics(&diagnostics)` through the very
 * `diagnostic_to_json` this client parses (`json.rs:52-124`). It carries FOUR
 * findings across TWO files — `/fib.py` (F401 and F841 fixable, F821 not) and
 * `/undef.py` (F821, not fixable) — which is exactly the attribution question:
 * only the dispatched file's fixable findings may be counted.
 */
const RUFF_VECTOR = path.resolve(
	import.meta.dirname,
	"../fixtures/ruff-json/ruff-0.16.8-json-output.snap.txt",
);

/** The upstream vector's own spelling of the file under analysis. */
const VECTOR_TARGET = "/fib.py";
/** The upstream vector's own spelling of the OTHER file it reports on. */
const VECTOR_SIBLING = "/undef.py";
/** F401 and F841 in that vector carry a `fix`; the two F821s do not. */
const VECTOR_FIXABLE = 2;

interface VectorItem {
	filename: string;
	fix: unknown;
}

/** The vector's findings with each file name rewritten to a real path. */
function ruffJson(spelling: { target: string; sibling: string }): string {
	const raw = fs.readFileSync(RUFF_VECTOR, "utf8");
	const items: VectorItem[] = JSON.parse(raw.split("---\n", 3)[2]);
	return JSON.stringify(
		items.map((item) => ({
			...item,
			filename:
				item.filename === VECTOR_TARGET ? spelling.target : spelling.sibling,
		})),
	);
}

/**
 * Does THIS filesystem fold case? Measured once against a real temp directory,
 * never asserted from `process.platform` (#3159 round 2: a platform-shaped case
 * claim redded EEXIST on the first real macOS run). APFS and NTFS answer true,
 * ext4 answers false, and the case-variant cell asserts the filesystem's own
 * answer on every lane instead of skipping off Windows.
 */
function hostFoldsPathCase(): boolean {
	const probe = fs.mkdtempSync(path.join(os.tmpdir(), "pi-lens-3286-case-"));
	try {
		fs.writeFileSync(path.join(probe, "probe.py"), "");
		return fs.existsSync(path.join(probe, "PROBE.py"));
	} finally {
		fs.rmSync(probe, { recursive: true, force: true });
	}
}

const HOST_FOLDS_PATH_CASE = hostFoldsPathCase();

const dirs: string[] = [];
let previousHome: string | undefined;

beforeEach(() => {
	// The cwd seam caps every marker walk at `$HOME`, so a fixture under the OS
	// temp root is out of reach of its own `pyproject.toml` unless the ceiling
	// moves with it (the #2894 suite pins the same rule).
	previousHome = process.env.HOME;
	process.env.HOME = fs.realpathSync(os.tmpdir());
	spawned.length = 0;
});

afterEach(() => {
	for (const dir of dirs.splice(0))
		fs.rmSync(dir, { recursive: true, force: true });
	if (previousHome === undefined) delete process.env.HOME;
	else process.env.HOME = previousHome;
	vi.clearAllMocks();
});

interface Observed {
	fixed: number;
	success: boolean;
	/** The absolute path the client handed ruff as argv. */
	argvPath: string;
	/** The spelling the vector was rewritten to. */
	reported: string;
}

/**
 * Drive the REAL `RuffClient.fixFileAsync` — the only production entry point
 * that parses ruff's JSON — with ruff reporting whatever `spell` builds from the
 * argv path. Throws when ruff was never spawned: an availability skip that read
 * as "nothing attached" would make every cell here vacuous (#448).
 */
async function runAutofix(
	spell: (paths: { argvPath: string; siblingPath: string }) => string,
): Promise<Observed> {
	const root = fs.realpathSync(
		fs.mkdtempSync(path.join(os.tmpdir(), "pi-lens-3286-")),
	);
	dirs.push(root);
	// NESTED, and never `process.cwd()`: ruff runs at the package that owns the
	// nearest `pyproject.toml` (#2894), so a reported spelling resolved against
	// the extension's own cwd names a different file.
	const pkg = path.join(root, "packages", "api");
	fs.mkdirSync(pkg, { recursive: true });
	fs.writeFileSync(path.join(root, "pyproject.toml"), "[tool.ruff]\n");
	fs.writeFileSync(path.join(pkg, "pyproject.toml"), "[tool.ruff]\n");
	const filePath = path.join(pkg, "fib.py");
	const siblingPath = path.join(pkg, "undef.py");
	fs.writeFileSync(filePath, "import os\n");
	fs.writeFileSync(siblingPath, "a\n");

	const argvPath = path.resolve(filePath);
	const reported = spell({ argvPath, siblingPath });
	safeSpawnAsync.mockImplementation(async (command, args, options) => {
		spawned.push({ command, args, cwd: options?.cwd });
		if (!args.includes("--output-format"))
			return { stdout: "", stderr: "", status: 0 };
		return {
			stdout: ruffJson({ target: reported, sibling: siblingPath }),
			stderr: "",
			status: 1,
		};
	});

	const { RuffClient } = await import("../../clients/ruff-client.js");
	const result = await new RuffClient().fixFileAsync(filePath, root);
	const scan = spawned.find((call) => call.args.includes("--output-format"));
	if (!scan)
		throw new Error(
			"ruff was never spawned with --output-format json — availability skipped " +
				"the run, so this cell would assert nothing about path attribution",
		);
	return {
		fixed: result.fixed,
		success: result.success,
		argvPath,
		reported,
	};
}

describe("ruff reported-path attribution (#3286)", () => {
	it("pins the upstream ruff vector's two files and two fixable findings (#3286)", () => {
		const items: VectorItem[] = JSON.parse(
			fs.readFileSync(RUFF_VECTOR, "utf8").split("---\n", 3)[2],
		);
		expect(items).toHaveLength(4);
		expect(new Set(items.map((item) => item.filename))).toEqual(
			new Set([VECTOR_TARGET, VECTOR_SIBLING]),
		);
		expect(items.filter((item) => item.fix !== null)).toHaveLength(
			VECTOR_FIXABLE,
		);
	});

	it("counts the absolute filename ruff echoes back as the dispatched file's own (#3286)", async () => {
		const observed = await runAutofix(({ argvPath }) => argvPath);
		expect(observed.success).toBe(true);
		expect(observed.fixed).toBe(VECTOR_FIXABLE);
	});

	it("does not count a sibling Python file's fixable findings (#3286)", async () => {
		const observed = await runAutofix(({ siblingPath }) => siblingPath);
		expect(observed.success).toBe(true);
		expect(observed.fixed).toBe(0);
	});

	// Both directions matter: on a case-folding host these are ONE file and the
	// findings must count (#209's drop); on a case-sensitive host they are two
	// files and a sibling's findings must not be charged to the edited one.
	it("treats a case-variant ruff filename exactly as this filesystem does (#3286)", async () => {
		const observed = await runAutofix(({ argvPath }) =>
			path.join(path.dirname(argvPath), path.basename(argvPath).toUpperCase()),
		);
		expect(observed.reported).not.toBe(observed.argvPath);
		expect(observed.success).toBe(true);
		expect(observed.fixed).toBe(HOST_FOLDS_PATH_CASE ? VECTOR_FIXABLE : 0);
	});
});
