#!/usr/bin/env node

import { randomUUID } from "node:crypto";
import {
	access,
	mkdir,
	mkdtemp,
	readdir,
	readFile,
	realpath,
	rename,
	rm,
	writeFile,
} from "node:fs/promises";
import { dirname, isAbsolute, join, relative, resolve, sep } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { build } from "esbuild";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const distDirectory = join(packageRoot, "dist");
const GENERATED_BANNER = [
	"// @generated by scripts/build-runtime.mjs; do not edit.",
	"// @ts-nocheck -- generated entries use .ts extensions for Pi's Jiti loader.",
].join("\n");
const GENERATED_TS_ENTRIES = ["index", "child-communication-bridge"];
const CHILD_BRIDGE_SOURCE = "src/child-communication-bridge.ts";

export async function buildRuntime({
	outputDirectory = distDirectory,
	validateOutput = validateGeneratedFiles,
} = {}) {
	const resolvedOutputDirectory = resolve(outputDirectory);
	await assertSafeOutputDirectory(resolvedOutputDirectory);
	await mkdir(dirname(resolvedOutputDirectory), { recursive: true });
	const stagingDirectory = await mkdtemp(
		join(dirname(resolvedOutputDirectory), ".pi-subagents-dist-"),
	);

	try {
		const result = await build({
			absWorkingDir: packageRoot,
			banner: { js: GENERATED_BANNER },
			bundle: true,
			chunkNames: "chunks/[name]-[hash]",
			entryNames: "[name]",
			entryPoints: {
				index: "src/index.ts",
				"child-communication-bridge": CHILD_BRIDGE_SOURCE,
			},
			format: "esm",
			legalComments: "none",
			metafile: true,
			outdir: stagingDirectory,
			packages: "external",
			platform: "node",
			sourcemap: true,
			splitting: true,
			target: "es2022",
			write: true,
		});
		validateEagerGraph(result.metafile);
		await prepareGeneratedRuntime(stagingDirectory);
		await validateOutput(stagingDirectory);
		await publishRuntime(stagingDirectory, resolvedOutputDirectory);
		return result.metafile;
	} catch (error) {
		await rm(stagingDirectory, { force: true, recursive: true });
		throw error;
	}
}

export function validateEagerGraph(metadata) {
	const outputs = metadata.outputs ?? {};
	const mainEntry = findEntry(outputs, "src/index.ts");
	const childEntry = findEntry(outputs, CHILD_BRIDGE_SOURCE);

	for (const output of Object.values(outputs)) {
		for (const inputPath of Object.keys(output.inputs ?? {})) {
			const normalized = normalizePath(inputPath);
			if (normalized.includes("/node_modules/")) {
				throw new Error(`Bundled package input: ${normalized}`);
			}
			if (!normalized.startsWith("/src/")) {
				throw new Error(`Bundled non-package source: ${normalized}`);
			}
		}
	}

	const eagerOutputs = collectEagerOutputs(outputs, mainEntry);
	const eagerInputs = new Set();
	for (const outputPath of eagerOutputs) {
		const output = outputs[outputPath];
		if (!output) continue;
		for (const inputPath of Object.keys(output.inputs ?? {})) {
			eagerInputs.add(normalizePath(inputPath));
		}
	}
	if ([...eagerInputs].some((input) => input.endsWith(`/${CHILD_BRIDGE_SOURCE}`))) {
		throw new Error(`Child-process entry is eager: ${CHILD_BRIDGE_SOURCE}`);
	}
	if (eagerOutputs.has(childEntry)) {
		throw new Error("Child-process entry is reachable from the main extension entry");
	}
	return { eagerInputs, eagerOutputs };
}

export async function validateGeneratedFiles(outputDirectory) {
	const files = await listFiles(outputDirectory);
	const runtimeFiles = files.filter((path) => path.endsWith(".ts") || path.endsWith(".js"));
	for (const entry of GENERATED_TS_ENTRIES) {
		if (!runtimeFiles.includes(`${entry}.ts`)) {
			throw new Error(`Generated runtime is missing ${entry}.ts`);
		}
		if (runtimeFiles.includes(`${entry}.js`)) {
			throw new Error(`Generated runtime retains ${entry}.js`);
		}
	}

	for (const runtimePath of runtimeFiles) {
		const source = await readFile(join(outputDirectory, runtimePath), "utf8");
		if (!source.startsWith(GENERATED_BANNER)) {
			throw new Error(`Generated marker is missing from ${runtimePath}`);
		}
		if (/from\s+["']\.\.?\/[^"']*src\//u.test(source)) {
			throw new Error(`Generated runtime imports authoritative source from ${runtimePath}`);
		}
		for (const specifier of relativeModuleSpecifiers(source)) {
			if (specifier.endsWith(".ts")) {
				throw new Error(`Generated runtime retains a .ts import in ${runtimePath}: ${specifier}`);
			}
			const targetPath = join(dirname(runtimePath), specifier).replaceAll("\\", "/");
			if (!files.includes(targetPath)) {
				throw new Error(`Generated runtime import is missing: ${runtimePath} -> ${specifier}`);
			}
		}
		if (!files.includes(`${runtimePath}.map`)) {
			throw new Error(`Source map is missing for ${runtimePath}`);
		}
	}

	const mainSource = await readFile(join(outputDirectory, "index.ts"), "utf8");
	if (!mainSource.includes('"./child-communication-bridge.ts"')) {
		throw new Error("Generated main entry does not reference the generated child bridge");
	}
}

async function assertSafeOutputDirectory(outputDirectory) {
	const relativeOutput = relative(packageRoot, outputDirectory);
	const firstSegment = relativeOutput.split(sep)[0];
	const isDefaultOutput = relativeOutput === "dist";
	const isTestOutput = firstSegment?.startsWith(".pi-subagents-build-test-");
	if (
		relativeOutput === "" ||
		relativeOutput === ".." ||
		relativeOutput.startsWith(`..${sep}`) ||
		isAbsolute(relativeOutput) ||
		(!isDefaultOutput && !isTestOutput)
	) {
		throw new Error(
			"Runtime output directory must be inside the package root and owned by the build",
		);
	}

	const realPackageRoot = await realpath(packageRoot);
	const realOutputParent = await realpath(dirname(outputDirectory));
	const relativeParent = relative(realPackageRoot, realOutputParent);
	if (
		relativeParent === ".." ||
		relativeParent.startsWith(`..${sep}`) ||
		isAbsolute(relativeParent)
	) {
		throw new Error("Runtime output parent must not escape the package root through a symlink");
	}
}

function findEntry(outputs, sourcePath) {
	const entry = Object.entries(outputs).find(([, output]) =>
		normalizePath(output.entryPoint ?? "").endsWith(`/${sourcePath}`),
	);
	if (!entry) throw new Error(`Generated runtime metadata has no ${sourcePath} entrypoint`);
	return entry[0];
}

function collectEagerOutputs(outputs, entryPath) {
	const eager = new Set();
	const pending = [entryPath];
	while (pending.length > 0) {
		const outputPath = pending.pop();
		if (!outputPath || eager.has(outputPath)) continue;
		eager.add(outputPath);
		for (const imported of outputs[outputPath]?.imports ?? []) {
			if (imported.external || imported.kind === "dynamic-import") continue;
			if (outputs[imported.path]) pending.push(imported.path);
		}
	}
	return eager;
}

async function prepareGeneratedRuntime(outputDirectory) {
	for (const entry of GENERATED_TS_ENTRIES) {
		const jsEntryPath = join(outputDirectory, `${entry}.js`);
		const tsEntryPath = join(outputDirectory, `${entry}.ts`);
		const jsMapPath = join(outputDirectory, `${entry}.js.map`);
		const tsMapPath = join(outputDirectory, `${entry}.ts.map`);
		const source = await readFile(jsEntryPath, "utf8");
		const rewritten = source.replace(
			`sourceMappingURL=${entry}.js.map`,
			`sourceMappingURL=${entry}.ts.map`,
		);
		if (rewritten === source) {
			throw new Error(`Generated ${entry} source map reference is missing`);
		}
		await writeFile(jsEntryPath, rewritten, "utf8");
		await rename(jsMapPath, tsMapPath);
		await rename(jsEntryPath, tsEntryPath);
	}
}

export async function publishRuntime(
	stagingDirectory,
	outputDirectory,
	{ renamePath = rename } = {},
) {
	const backupDirectory = `${outputDirectory}.backup-${randomUUID()}`;
	const hadPreviousOutput = await exists(outputDirectory);
	if (hadPreviousOutput) await renamePath(outputDirectory, backupDirectory);
	try {
		await renamePath(stagingDirectory, outputDirectory);
	} catch (error) {
		if (hadPreviousOutput) {
			await rm(outputDirectory, { force: true, recursive: true });
			await renamePath(backupDirectory, outputDirectory);
		}
		throw error;
	}
	if (hadPreviousOutput) await rm(backupDirectory, { force: true, recursive: true });
}

async function exists(path) {
	try {
		await access(path);
		return true;
	} catch {
		return false;
	}
}

async function listFiles(directory, prefix = "") {
	const files = [];
	for (const entry of await readdir(join(directory, prefix), { withFileTypes: true })) {
		const relativePath = join(prefix, entry.name);
		if (entry.isDirectory()) files.push(...(await listFiles(directory, relativePath)));
		else if (entry.isFile()) files.push(relativePath.replaceAll("\\", "/"));
	}
	return files.sort();
}

function relativeModuleSpecifiers(source) {
	const specifiers = [];
	const pattern =
		/(?:\b(?:import|export)\s+(?:[^"'()]*?\s+from\s*)?|\bimport\s*\(\s*)["'](\.\.?\/[^"']+)["']/gu;
	for (const match of source.matchAll(pattern)) {
		if (match[1]) specifiers.push(match[1]);
	}
	return specifiers;
}

function normalizePath(path) {
	const normalized = path.replaceAll("\\", "/");
	if (!isAbsolute(path)) return `/${normalized.replace(/^\.\//u, "")}`;
	return `/${relative(packageRoot, path).replaceAll("\\", "/")}`;
}

const invokedPath = process.argv[1] ? pathToFileURL(resolve(process.argv[1])).href : undefined;
if (invokedPath === import.meta.url) await buildRuntime();
