#!/usr/bin/env node

import { readFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { createRuntimeBuilder } from "../../../scripts/runtime-builder.mjs";

const childBridgeSource = "src/child-communication-bridge.ts";
const childReadinessSource = "src/child-readiness-probe.ts";
const childEntrySources = [childBridgeSource, childReadinessSource];

export const { buildRuntime, validateEagerGraph, validateGeneratedFiles, publishRuntime } = createRuntimeBuilder({
  packageRoot: resolve(dirname(fileURLToPath(import.meta.url)), ".."),
  temporaryPrefix: ".pi-subagents",
  banner: [
    "// @generated by scripts/build-runtime.mjs; do not edit.",
    "// @ts-nocheck -- generated entries use .ts extensions for Pi's Jiti loader.",
  ].join("\n"),
  entries: {
    index: "src/index.ts",
    "child-communication-bridge": childBridgeSource,
    "child-readiness-probe": childReadinessSource,
  },
  validateGraph({ allInputs, eagerInputs, eagerOutputs, entryPaths }) {
    for (const input of allInputs) {
      if (!input.startsWith("/src/")) throw new Error(`Bundled non-package source: ${input}`);
    }
    for (const source of childEntrySources) {
      if ([...eagerInputs].some((input) => input.endsWith(`/${source}`))) {
        throw new Error(`Child-process entry is eager: ${source}`);
      }
    }
    for (const entry of ["child-communication-bridge", "child-readiness-probe"]) {
      if (eagerOutputs.has(entryPaths[entry])) {
        throw new Error(`Child-process entry is reachable from the main extension entry: ${entry}`);
      }
    }
  },
  async validateFiles({ outputDirectory }) {
    const mainSource = await readFile(join(outputDirectory, "index.ts"), "utf8");
    for (const [file, label] of [
      ["child-communication-bridge.ts", "child bridge"],
      ["child-readiness-probe.ts", "child readiness probe"],
    ]) {
      if (!mainSource.includes(`"./${file}"`)) {
        throw new Error(`Generated main entry does not reference the generated ${label}`);
      }
    }
  },
});

const invokedPath = process.argv[1] ? pathToFileURL(resolve(process.argv[1])).href : undefined;
if (invokedPath === import.meta.url) await buildRuntime();
