/**
 * Centralized generated/artifact detection.
 *
 * This module is intentionally lightweight and synchronous because it is used by
 * hot-path source collection and dispatch role detection. It combines cheap
 * path/name heuristics with optional header inspection for common generated-code
 * banners.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { isWindowsPath } from "./path-utils.js";
import { BoundedLruCache } from "./bounded-cache.js";

const DEFAULT_HEADER_BYTES = 4096;

const GENERATED_DIR_NAMES = new Set([
	"generated",
	"__generated__",
	"codegen",
	"__codegen__",
	"generated-sources",
	"generated_sources",
	"dist",
	"openapi-generated",
	".openapi-generator",
]);

const GENERATED_HEADER_PATTERNS = [
	/@generated\b/i,
	/@ts-nocheck\b/i,
	/\bcode generated\b/i,
	/\bdo not edit\b/i,
	/\bautomatically generated\b/i,
	/\bthis file was generated\b/i,
	/\bgenerated by protoc\b/i,
	/\bgenerated by graphql-code-generator\b/i,
	/\bgenerated by openapi-generator\b/i,
	/\bgenerated by swagger codegen\b/i,
];

// Package-manager lockfiles are generated, never hand-written source — and
// often huge (a 10MB package-lock.json is unremarkable). Broadened enumeration
// (#894) made the .json/.yaml ones visible to project-wide walks; filtering
// them here (the generated-file authority) removes them from every collector
// at once. Compared lowercased, like GENERATED_DIR_NAMES.
const LOCKFILE_NAMES = new Set([
	"package-lock.json",
	"packages.lock.json",
	"npm-shrinkwrap.json",
	"pnpm-lock.yaml",
	"yarn.lock",
	"bun.lock",
	"cargo.lock",
	"composer.lock",
	"gemfile.lock",
	"poetry.lock",
	"uv.lock",
	"go.sum",
]);

const GENERATED_FILE_PATTERNS = [
	/(^|[._-])generated([._-]|$)/i,
	/(^|[._-])gen([._-])/i,
	/_generated\.(go|rs|py|rb|java|kt|ts|tsx|js|jsx|mjs|cjs)$/i,
	/_gen\.(go|rs|py|rb|java|kt|ts|tsx|js|jsx|mjs|cjs)$/i,
	/\.pb\.(go|ts|tsx|js|jsx|mjs|cjs)$/i,
	/_pb2(_grpc)?\.py$/i,
	/\.sql\.(go|ts|js)$/i,
	/_sqlc\.go$/i,
	/\.g\.([jt]sx?|mjs|cjs|rs|go)$/i,
];

// #1107 phase 2 review (P2, maintainer decision): minified/bundle/chunk
// output is intentionally NOT eligible for the content-probe escape hatch
// below and lives in the STRONG tier instead, alongside lockfiles — the
// escape hatch's premises fail structurally for this class:
//  - Hand-written-with-this-name probability is ~0 (nobody names a source
//    file `app.min.js`/`vendor.bundle.js` by hand).
//  - The header-probe leg is dead for it: minifiers strip comments/banners
//    by design, so a real minified bundle essentially never carries a
//    `GENERATED_HEADER_PATTERNS` match — the probe can never confirm it, so
//    under the WEAK-tier escape hatch this class would ALWAYS be "kept" via
//    the no-evidence branch, not "kept sometimes." That inverts the
//    heuristic from "usually right, occasionally rescued" to "never right."
//  - The sibling-probe leg is also dead for it: `findSourceSibling` looks
//    for a `.ts`/`.tsx`/etc. twin at the SAME stem (`app.min.ts` next to
//    `app.min.js`), which is never how minified bundles are produced — the
//    real source twin is `app.ts`/`app.js` at a DIFFERENT stem, which the
//    sibling probe does not check. So the "does a hand-written source twin
//    exist" question this class actually needs answered is structurally
//    unreachable, not merely unresolved.
// Both dead legs mean this class would be a permanent override — never
// re-confirmed by either evidence check — so it is excluded from the WEAK
// tier entirely and always skipped, like a lockfile.
const MINIFIED_BUNDLE_FILE_PATTERNS = [
	/\.min\.(js|mjs|cjs|css)$/i,
	/\.(bundle|chunk)\.(js|mjs|cjs|css)$/i,
];

const DECLARATION_FILE_PATTERNS = [/\.d\.ts$/i, /\.d\.mts$/i, /\.d\.cts$/i];

export interface GeneratedArtifactOptions {
	/** Optional file content or prefix. When omitted, content markers are skipped. */
	content?: string;
	/** Read a small file prefix to detect generated-code banners. */
	readContentHeader?: boolean;
	/** Number of bytes to read when readContentHeader is true. */
	maxHeaderBytes?: number;
	/** Treat declaration stubs (.d.ts/.d.mts/.d.cts) as artifacts. */
	includeDeclarations?: boolean;
}

function pathSegments(filePath: string): string[] {
	return path
		.normalize(filePath)
		.split(/[\\/]+/)
		.filter(Boolean);
}

/**
 * Shape-aware basename: a WINDOWS-SHAPED path (drive letter or UNC prefix,
 * per `isWindowsPath`) is parsed with `path.win32.basename` regardless of the
 * running OS, mirroring the `detectFileRole` fix in `file-role.ts` (refs
 * #1152, #1150, #1161 — defect shape 2: a host-default `path` fn inside a
 * shape-committed branch follows the *host* OS, so on Linux CI a `C:\...`
 * path has no POSIX separator and the module-default `basename` returns the
 * whole string unchanged, missing exact-name lookups like `LOCKFILE_NAMES`).
 * Native same-OS paths (POSIX on Linux, win32 on Windows) are unaffected —
 * on win32 this is a no-op since `win32.basename` already equals the module
 * default there.
 */
function basenameForShape(filePath: string): string {
	return isWindowsPath(filePath)
		? path.win32.basename(filePath)
		: path.basename(filePath);
}

export function isGeneratedArtifactDirectoryName(dirName: string): boolean {
	return GENERATED_DIR_NAMES.has(dirName.trim().toLowerCase());
}

export function isDeclarationFile(filePath: string): boolean {
	const base = basenameForShape(filePath).toLowerCase();
	return DECLARATION_FILE_PATTERNS.some((pattern) => pattern.test(base));
}

/**
 * STRONG evidence a path is generated/artifact output: it lives under a
 * directory segment that itself looks generated (`generated/`, `codegen/`,
 * …), its basename is a known package-manager lockfile, or it matches a
 * minified/bundle/chunk output pattern (see
 * {@link MINIFIED_BUNDLE_FILE_PATTERNS}'s doc for why that class is STRONG,
 * not WEAK). All three are treated as conclusive — no content-probe escape
 * hatch (#1107 phase 2) applies to any of them. A lockfile is never
 * hand-written; a generated-dir SEGMENT match here only fires for callers
 * that check a single path without having walked (directory-level pruning
 * already removes the walk-time case in `shouldRecurseIntoDir`, so this
 * branch is effectively a belt-and-braces check for non-walk callers like
 * `file-role.ts` and `project-scan-policy.ts`).
 */
function hasStrongGeneratedArtifactPath(filePath: string): boolean {
	const segments = pathSegments(filePath);
	const dirSegments = segments.slice(0, -1);
	if (
		dirSegments.some((segment) => isGeneratedArtifactDirectoryName(segment))
	) {
		return true;
	}

	const base = basenameForShape(filePath);
	if (LOCKFILE_NAMES.has(base.toLowerCase())) return true;
	return MINIFIED_BUNDLE_FILE_PATTERNS.some((pattern) => pattern.test(base));
}

/**
 * WEAK evidence: the basename alone matches a generated-file NAME pattern
 * (e.g. `gen.ts`, `foo_generated.go`, `user.pb.go`). Unlike the strong path
 * check above, a name-only match is not conclusive — a hand-written file can
 * innocently contain "gen" in its name. #1107 phase 2's content-probe escape
 * hatch (see `classifyGeneratedOrArtifactDetailed`) requires corroborating
 * evidence (a source sibling, checked upstream by walk-driven callers, or a
 * generated-code header) before treating a WEAK-only match as an artifact.
 * Minified/bundle/chunk output (`bar.min.js`, `vendor.bundle.js`) is
 * deliberately NOT in this WEAK set — see
 * {@link MINIFIED_BUNDLE_FILE_PATTERNS}'s doc for why that class is STRONG
 * instead (the escape hatch's evidence checks are structurally dead for it).
 */
function hasWeakGeneratedFileNamePattern(filePath: string): boolean {
	const base = basenameForShape(filePath);
	return GENERATED_FILE_PATTERNS.some((pattern) => pattern.test(base));
}

function hasGeneratedArtifactContent(content: string): boolean {
	const header = content.slice(0, DEFAULT_HEADER_BYTES);
	return GENERATED_HEADER_PATTERNS.some((pattern) => pattern.test(header));
}

/**
 * Content-shape classifier for machine-emitted text (refs #2346).
 *
 * A saved/scraped page, a minified bundle, or an embedded data blob is one
 * giant line or a handful, so mean non-empty line length on already-loaded
 * content is a language-agnostic generated signature. Extensions covered by
 * name patterns can never cover it (`.html` has no `.min.`-style convention),
 * which is the exact gap #2346 hit: a 269 KB scraped page on 38 lines (mean
 * ~7084/line) drew the full auxiliary scanner stack.
 *
 * The threshold is derived from measurement ON THE SHIPPED STATISTIC (the
 * 4096-byte header/prefix mean, not full-content means — the two differ by
 * 3-7x on long-paragraph prose). Measured 2026-08-28 across all 3,331 text
 * files in this repo: the maximum hand-authored prefix mean is 453.2
 * (`docs/analysisall.md`, unwrapped prose paragraphs); the widest
 * hand-authored one-line shape observed anywhere probed is a ~2048-char
 * barrel re-export. The threshold of 2500 sits ~5.5x above the repo's worst
 * prose file and above every observed hand-authored shape, while the #2346
 * evidence file (269 KB / 38 lines) remains far above it. Direction of
 * error is deliberate per #1107: a borderline machine-emitted file that
 * slips through (false KEEP) costs noise once; a hand-authored file
 * silently classified generated (false DROP) vanishes from scans with no
 * signal. Both constants are exported so the tuning claim is checkable and
 * the regression tests pin the margin probes on both sides.
 *
 * Prefix-path quantization: on the 4096-byte header/prefix paths the
 * achievable means are quantized (~4096 for a one-line prefix, ~2048 for
 * two lines), so any threshold in (2048, 4096] behaves as "is the first
 * line longer than 4096 bytes". A machine-emitted file with 2500-4000-char
 * lines is missed on the prefix path even though its full content would
 * classify — the deliberate false-KEEP direction, not a continuous 5.5x
 * margin there. The full-content path (dispatch) has no such quantization.
 *
 * Degenerate cases are guarded: content below the minimum byte length never
 * classifies generated on line shape alone (a 500-byte single-line config
 * file is not machine-emitted evidence), and an empty or whitespace-only
 * file yields a zero mean and stays source.
 */
export const MACHINE_EMITTED_LINE_SHAPE_MIN_CONTENT = 2048;
export const MACHINE_EMITTED_LINE_SHAPE_MEAN_THRESHOLD = 2500;

export interface MachineEmittedLineShape {
	/** True when the content shape classifies as generated. */
	generated: boolean;
	/** Mean length of the content's non-empty lines in UTF-16 code units. */
	meanLineLength: number;
}

export function classifyMachineEmittedLineShape(
	content: string,
): MachineEmittedLineShape {
	const contentLength = content.length;
	if (contentLength < MACHINE_EMITTED_LINE_SHAPE_MIN_CONTENT) {
		return { generated: false, meanLineLength: 0 };
	}
	// Single O(contentLength) pass. Deliberately no `split(/\r?\n/)`: a
	// minified blob's single line can be megabytes, and splitting allocates a
	// copy of the whole content. `\r` contributes nothing to line length so a
	// CRLF line is measured by its display width.
	let nonEmptyLineTotal = 0;
	let nonEmptyLineCount = 0;
	let currentLineLength = 0;
	for (let i = 0; i < contentLength; i++) {
		const code = content.charCodeAt(i);
		if (code === 10 /* \n */) {
			if (currentLineLength > 0) {
				nonEmptyLineTotal += currentLineLength;
				nonEmptyLineCount += 1;
			}
			currentLineLength = 0;
		} else if (code !== 13 /* \r */) {
			currentLineLength += 1;
		}
	}
	if (currentLineLength > 0) {
		nonEmptyLineTotal += currentLineLength;
		nonEmptyLineCount += 1;
	}
	if (nonEmptyLineCount === 0) return { generated: false, meanLineLength: 0 };
	const meanLineLength = nonEmptyLineTotal / nonEmptyLineCount;
	return {
		generated: meanLineLength > MACHINE_EMITTED_LINE_SHAPE_MEAN_THRESHOLD,
		meanLineLength,
	};
}

// Memoize the header analysis (banner + line shape) per (path, mtimeMs, size,
// maxBytes). The 4 KB header read (openSync + readSync + closeSync) is ~70% of
// the per-file cost in `collectSourceFiles`, and the same files are re-scanned
// by multiple background scanners (todo, project-diagnostics, language-profile)
// every session/turn. Keying on mtime+size makes the memo self-invalidating:
// an edited file misses the cache and is re-read. A single stat replaces the
// open/read/close on a hit. Bounded to avoid unbounded growth on giant repos.
const HEADER_VERDICT_MEMO_CAP = 50_000;
const headerAnalysisMemo = new BoundedLruCache<string, FileHeaderAnalysis>(
	HEADER_VERDICT_MEMO_CAP,
);

/** Test-only: drop the header-analysis memo so fixtures don't leak across cases. */
export function _resetGeneratedArtifactCaches(): void {
	headerAnalysisMemo.clear();
}

function readFileHeader(
	filePath: string,
	maxBytes = DEFAULT_HEADER_BYTES,
): string | undefined {
	let fd: number | undefined;
	try {
		fd = fs.openSync(filePath, "r");
		const buffer = Buffer.alloc(Math.max(0, maxBytes));
		const bytesRead = fs.readSync(fd, buffer, 0, buffer.length, 0);
		return buffer.toString("utf8", 0, bytesRead);
	} catch {
		return undefined;
	} finally {
		if (fd !== undefined) {
			try {
				fs.closeSync(fd);
			} catch {
				/* ignore close errors */
			}
		}
	}
}

/**
 * Memoized content analysis of a file's header: the generated-code banner
 * verdict AND the line-shape classification, both computed over the bytes
 * already read for the header probe (no second read). Returns `undefined`
 * when the file cannot be stat'd. Keyed on path + mtime + size so edits
 * invalidate it.
 */
interface FileHeaderAnalysis {
	banner: boolean;
	shape: MachineEmittedLineShape;
}

function analyzeFileHeader(
	filePath: string,
	maxBytes: number,
): FileHeaderAnalysis | undefined {
	let key: string;
	try {
		const st = fs.statSync(filePath);
		key = `${st.mtimeMs}:${st.size}:${maxBytes}:${filePath}`;
	} catch {
		return undefined;
	}
	const cached = headerAnalysisMemo.get(key);
	if (cached !== undefined) return cached;
	const header = readFileHeader(filePath, maxBytes);
	// A header that cannot be read classifies as clean (no banner, no shape
	// signal) and is memoized as such, mirroring the pre-#2346 fallback.
	const analysis: FileHeaderAnalysis =
		header === undefined
			? { banner: false, shape: { generated: false, meanLineLength: 0 } }
			: {
					banner: hasGeneratedArtifactContent(header),
					shape: classifyMachineEmittedLineShape(header),
				};
	headerAnalysisMemo.set(key, analysis);
	return analysis;
}

/**
 * Verdict of {@link classifyGeneratedOrArtifact}:
 *  - `"generated"`: confirmed generated/artifact output — skip it. Either a
 *    STRONG path match (generated dir segment, lockfile, minified/bundle/
 *    chunk output), an explicit declaration-file opt-in, a confirmed
 *    generated-code content header, or (only when no header probe was
 *    possible/enabled) a WEAK name-only match falling back to the
 *    pre-#1107-phase-2 trust-the-name behavior.
 *  - `"override"`: #1107 phase 2's content-probe escape hatch fired — a WEAK
 *    name-only match (e.g. `gen.ts`) that a content-header probe did NOT
 *    confirm. Kept, not skipped; callers that track observability should
 *    count this distinctly from a genuine `"clean"` (never-flagged) file so
 *    the heuristic's rescues stay visible.
 *  - `"clean"`: no evidence at all — never matched any heuristic.
 */
export type GeneratedArtifactVerdict = "generated" | "override" | "clean";

/**
 * WHICH evidence produced a `"generated"` verdict (undefined for `"override"`/
 * `"clean"`) — #1107 phase 2 review: a tool-facing skip notice must not treat
 * every `"generated"` verdict as equally "at risk," or it fires permanently
 * on every real repo (a `package-lock.json` alone would trip it forever).
 *  - `"strong"`: STRONG path evidence (generated dir segment, lockfile,
 *    minified/bundle/chunk output) or the explicit declaration-file opt-in —
 *    no content probe involved, conclusive by construction. Expected on
 *    almost every repo and NOT a coverage-hole signal.
 *  - `"content"`: a WEAK name match CONFIRMED by a generated-code header (or
 *    caller-supplied `content`) — the escape hatch checked and the evidence
 *    came back positive. Also not a coverage-hole signal: this is exactly
 *    the case #1107 phase 2 wanted to keep skipping.
 *  - `"line-shape"`: NO name signal at all — the content's line shape alone
 *    classifies it as machine-emitted (mean non-empty line length above
 *    {@link MACHINE_EMITTED_LINE_SHAPE_MEAN_THRESHOLD}, content above
 *    {@link MACHINE_EMITTED_LINE_SHAPE_MIN_CONTENT}). #2346: a scraped or
 *    minified page whose name carries no generated marker. Distinct from
 *    `"name-only"` on purpose: this verdict has content EVIDENCE (the shape
 *    measurement), so it is not part of the residual at-risk bucket.
 *  - `"name-only"`: a WEAK name match trusted with NO corroborating evidence
 *    check performed at all — only reachable when the caller supplied
 *    neither `content` nor `readContentHeader:true` (source-filter.ts's
 *    default project-walk path always enables the header probe, so this
 *    should be rare-to-zero in practice; it exists for callers that opt out
 *    of the probe for performance and therefore get the old, unverified
 *    trust-the-name behavior). This is the ONLY residual "at risk" bucket
 *    the #1107 phase 2 escape hatch could not evaluate — a tool-facing
 *    notice should key off this, not the full `"generated"` count.
 */
export type GeneratedArtifactEvidence =
	| "strong"
	| "content"
	| "line-shape"
	| "name-only";

export interface GeneratedArtifactClassification {
	verdict: GeneratedArtifactVerdict;
	/** Only set when `verdict === "generated"`. See {@link GeneratedArtifactEvidence}. */
	evidence?: GeneratedArtifactEvidence;
	/**
	 * Only set when `verdict === "generated"` AND `evidence === "line-shape"`:
	 * the mean non-empty line length measured on the content that decided it.
	 */
	lineShapeMean?: number;
}

/**
 * The full verdict (+ evidence tier) behind {@link isGeneratedOrArtifact}'s
 * boolean, exposing the #1107 phase 2 content-probe escape hatch: a WEAK
 * name-only match (see {@link hasWeakGeneratedFileNamePattern}) is no longer
 * skipped on the name alone — it additionally requires a generated-code
 * header in the first few KB (`hasGeneratedArtifactContent`/
 * `fileHeaderLooksGenerated`) before being treated as an artifact. Evidence
 * check order is cheapest-first: STRONG path (dir segment/lockfile/minified-
 * bundle, no filesystem probe) → declaration opt-in → content/header probe,
 * so the (often already-open) file read only happens for the WEAK-match case
 * that actually needs it.
 *
 * Evidence class (a) from the issue — "does a higher-precedence hand-written
 * source SIBLING exist?" — is deliberately NOT re-implemented here: it is
 * `source-filter.ts`'s `findSourceSibling`/`isBuildArtifact` (this module has
 * no filesystem-sibling-probe cache, and `source-filter.ts` already imports
 * this module, so adding a reverse import would be circular). Both call
 * sites that matter (`classifyEntry`, `filterSourceFiles` in
 * `source-filter.ts`) already probe for a sibling BEFORE reaching this
 * function and short-circuit on a hit, so by the time this function runs for
 * those callers evidence (a) has already come back negative. Non-walk
 * callers with no upstream sibling probe (`file-role.ts`'s content-based
 * check, `project-scan-policy.ts`'s single-path `shouldSkipProjectPath`)
 * evaluate evidence (b) only — a documented, narrower guarantee than the
 * walk path's.
 *
 * Tradeoff (documented per the issue): when NEITHER piece of evidence
 * confirms a WEAK name match, the file is KEPT. This can rescue a real
 * headerless generated file with no source twin into a walk/graph/index that
 * previously silently dropped it — accepted per #1107: a false-KEEP (an
 * agent sees one extra file it must itself judge) is strictly less harmful
 * than a silent false-DROP (a real file invisibly never analyzed at all).
 * This tradeoff deliberately does NOT extend to minified/bundle/chunk output
 * — see {@link MINIFIED_BUNDLE_FILE_PATTERNS}'s doc for why that class is
 * STRONG (always skipped, no escape hatch) rather than WEAK.
 */
export function classifyGeneratedOrArtifactDetailed(
	filePath: string,
	options: GeneratedArtifactOptions = {},
): GeneratedArtifactClassification {
	if (hasStrongGeneratedArtifactPath(filePath)) {
		return { verdict: "generated", evidence: "strong" };
	}
	if (options.includeDeclarations && isDeclarationFile(filePath)) {
		return { verdict: "generated", evidence: "strong" };
	}

	const weakNameMatch = hasWeakGeneratedFileNamePattern(filePath);

	if (options.content !== undefined) {
		if (hasGeneratedArtifactContent(options.content)) {
			return { verdict: "generated", evidence: "content" };
		}
		const shape = classifyMachineEmittedLineShape(options.content);
		if (shape.generated) {
			return {
				verdict: "generated",
				evidence: "line-shape",
				lineShapeMean: shape.meanLineLength,
			};
		}
		return { verdict: weakNameMatch ? "override" : "clean" };
	}

	if (options.readContentHeader) {
		const analysis = analyzeFileHeader(
			filePath,
			options.maxHeaderBytes ?? DEFAULT_HEADER_BYTES,
		);
		if (analysis?.banner) {
			return { verdict: "generated", evidence: "content" };
		}
		if (analysis?.shape.generated) {
			return {
				verdict: "generated",
				evidence: "line-shape",
				lineShapeMean: analysis.shape.meanLineLength,
			};
		}
		return { verdict: weakNameMatch ? "override" : "clean" };
	}

	// No content/header probe was supplied or enabled: there is no cheap way
	// to evaluate evidence (b) here, so a WEAK name match falls back to the
	// pre-#1107-phase-2 behavior (trust the name, skip it) rather than
	// silently activating the escape hatch for callers that opted out of the
	// probe for performance. The escape hatch only activates when a header
	// probe actually ran and did not confirm. Evidence "name-only" — the one
	// residual at-risk bucket, see {@link GeneratedArtifactEvidence}.
	return weakNameMatch
		? { verdict: "generated", evidence: "name-only" }
		: { verdict: "clean" };
}

/** Verdict-only convenience wrapper over {@link classifyGeneratedOrArtifactDetailed}. */
export function classifyGeneratedOrArtifact(
	filePath: string,
	options: GeneratedArtifactOptions = {},
): GeneratedArtifactVerdict {
	return classifyGeneratedOrArtifactDetailed(filePath, options).verdict;
}

export function isGeneratedOrArtifact(
	filePath: string,
	options: GeneratedArtifactOptions = {},
): boolean {
	return classifyGeneratedOrArtifact(filePath, options) === "generated";
}
