/**
 * Guards the generated rule catalogs (docs/ast-grep_rules_catalog.md,
 * docs/tree-sitter_rules_catalog.md) against drift: if a rule is added/removed
 * without regenerating, `gen-rule-catalogs.mjs --check` fails, and so does this.
 */

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const REPO_ROOT = path.resolve(
	path.dirname(fileURLToPath(import.meta.url)),
	"../..",
);
const GEN = path.join(REPO_ROOT, "scripts/gen-rule-catalogs.mjs");

describe("generated rule catalogs", () => {
	it("are in sync with the rule files (gen --check passes)", () => {
		expect(() =>
			execFileSync("node", [GEN, "--check"], {
				cwd: REPO_ROOT,
				stdio: "pipe",
			}),
		).not.toThrow();
	});

	it("both catalog files exist and group rules by language", () => {
		for (const f of [
			"docs/ast-grep_rules_catalog.md",
			"docs/tree-sitter_rules_catalog.md",
		]) {
			const md = fs.readFileSync(path.join(REPO_ROOT, f), "utf8");
			expect(md).toContain("GENERATED by scripts/gen-rule-catalogs.mjs");
			expect(md).toMatch(/^### .+ \(\d+\)$/m); // a "### Language (N)" heading
		}
	});
});
