import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { afterEach, describe, expect, it, vi } from "vitest";
import type { LatencyEntry } from "../clients/latency-logger.js";

// #1107 observability-first slice: the source walk silently drops real files
// whose NAMES match generated-artifact heuristics (e.g. a real `src/gen.ts`)
// with no visibility anywhere. This test file exercises the new per-walk skip
// counters on `SourceCollectionResult` and the one-line rollup log emitted
// through the existing `logLatency` channel when nonzero.
//
// `logLatency` no-ops in test mode (`isTestMode()`), so the log-line
// assertions mock the module — same pattern as
// `tests/clients/cache-observability.test.ts`.
const latencyEntries = vi.hoisted(() => [] as LatencyEntry[]);
vi.mock("../clients/latency-logger.js", () => ({
	logLatency: (entry: LatencyEntry) => latencyEntries.push(entry),
}));

import {
	collectSourceFilesWithBudget,
	collectSourceFilesWithBudgetAsync,
} from "../clients/source-filter.js";
import { removeTempDirSync } from "./clients/test-utils.js";

const cleanups: Array<() => void> = [];

afterEach(() => {
	while (cleanups.length > 0) cleanups.pop()?.();
	latencyEntries.length = 0;
});

function mkTempDir(): string {
	const dir = fs.mkdtempSync(path.join(os.tmpdir(), "source-filter-skip-obs-"));
	cleanups.push(() => removeTempDirSync(dir));
	return dir;
}

/**
 * A normal file + a real source file whose NAME matches the generated-
 * artifact heuristic (`isGeneratedOrArtifact`'s `/(^|[._-])gen([._-])/`
 * pattern matches "gen.ts") AND carries a recognized generated-code header
 * (so #1107 phase 2's content-probe escape hatch does NOT rescue it — see
 * `source-filter-generated-escape-hatch.test.ts` for the rescued case) + a
 * compiled-looking sibling that gets skipped by the artifact-probe
 * (sibling-source) path — one skip of each observability class, plus one
 * kept file, in a single walk.
 */
function createMixedSkipTree(): string {
	const dir = mkTempDir();
	// Kept: ordinary hand-written source, no name/sibling match.
	fs.writeFileSync(
		path.join(dir, "alpha.ts"),
		"export function alphaFn() {\n\treturn 1;\n}\n",
	);
	// Skipped via the generated/artifact NAME heuristic (classifyEntry's
	// `shouldSkipGeneratedOrArtifact` -> `generatedOrArtifactSkips`). The
	// generated-code header confirms the name-only match (#1107 phase 2) so
	// this stays a genuine skip rather than an override.
	fs.writeFileSync(
		path.join(dir, "gen.ts"),
		"// Code generated by tool. DO NOT EDIT.\nexport function genFn() {\n\treturn 1;\n}\n",
	);
	// Skipped via the artifact-probe / sibling-source path (classifyEntry's
	// `isBuildArtifact` -> `buildArtifactSkips`): `compiled.js` has a
	// higher-precedence `.ts` twin sitting right next to it.
	fs.writeFileSync(
		path.join(dir, "compiled.ts"),
		"export function compiledFn() {\n\treturn 1;\n}\n",
	);
	fs.writeFileSync(
		path.join(dir, "compiled.js"),
		"exports.compiledFn = function () { return 1; };\n",
	);
	return dir;
}

describe("source walk skip observability (#1107)", () => {
	it("sync walk: counts generated-name and artifact-probe skips separately and surfaces them on the result", () => {
		const dir = createMixedSkipTree();
		const result = collectSourceFilesWithBudget(dir);

		expect(result.files.sort()).toEqual(
			[path.join(dir, "alpha.ts"), path.join(dir, "compiled.ts")].sort(),
		);
		expect(result.generatedOrArtifactSkips).toBe(1);
		expect(result.buildArtifactSkips).toBe(1);
		expect(result.generatedDirSkips).toBe(0);
		expect(result.generatedNameOverrides).toBe(0);

		const summary = latencyEntries.find(
			(e) => e.phase === "source_walk_skip_summary",
		);
		expect(summary).toBeDefined();
		expect(summary?.metadata).toEqual({
			generatedOrArtifactSkips: 1,
			buildArtifactSkips: 1,
			generatedDirSkips: 0,
			generatedNameOverrides: 0,
			generatedNameOnlySkips: 0,
		});
	});

	it("async walk: agrees with the sync walk on skip counts and result fields", async () => {
		const dir = createMixedSkipTree();
		const result = await collectSourceFilesWithBudgetAsync(dir);

		expect(result.files.sort()).toEqual(
			[path.join(dir, "alpha.ts"), path.join(dir, "compiled.ts")].sort(),
		);
		expect(result.generatedOrArtifactSkips).toBe(1);
		expect(result.buildArtifactSkips).toBe(1);

		const summary = latencyEntries.find(
			(e) => e.phase === "source_walk_skip_summary",
		);
		expect(summary).toBeDefined();
	});

	it("emits no log line and reports zero counters when a walk has no name/artifact-probe skips", () => {
		const dir = mkTempDir();
		fs.writeFileSync(
			path.join(dir, "alpha.ts"),
			"export function alphaFn() {\n\treturn 1;\n}\n",
		);
		fs.writeFileSync(
			path.join(dir, "beta.ts"),
			"export function betaFn() {\n\treturn 1;\n}\n",
		);

		const result = collectSourceFilesWithBudget(dir);

		expect(result.files.length).toBe(2);
		expect(result.generatedOrArtifactSkips).toBe(0);
		expect(result.buildArtifactSkips).toBe(0);
		expect(
			latencyEntries.some((e) => e.phase === "source_walk_skip_summary"),
		).toBe(false);
	});

	it("emits no log line on a zero-skip async walk either", async () => {
		const dir = mkTempDir();
		fs.writeFileSync(
			path.join(dir, "alpha.ts"),
			"export function alphaFn() {\n\treturn 1;\n}\n",
		);

		const result = await collectSourceFilesWithBudgetAsync(dir);

		expect(result.generatedOrArtifactSkips).toBe(0);
		expect(result.buildArtifactSkips).toBe(0);
		expect(
			latencyEntries.some((e) => e.phase === "source_walk_skip_summary"),
		).toBe(false);
	});
});

// #1107 phase 2 item 1: directory-level pruning was previously uncounted —
// `shouldRecurseIntoDir`'s `isGeneratedArtifactDirectoryName` branch pruned a
// whole `generated/`/`codegen/` directory and reported zero, even if it held
// real hand-written files. `generatedDirSkips` counts the PRUNED DIRECTORY
// itself (one event), never the files inside it — enumerating those would
// defeat the point of pruning at the directory level.
describe("directory-level generated-artifact skip counting (#1107 phase 2)", () => {
	function createDirSkipTree(): string {
		const dir = mkTempDir();
		fs.writeFileSync(
			path.join(dir, "alpha.ts"),
			"export function alphaFn() {\n\treturn 1;\n}\n",
		);
		// An entire directory pruned by name — multiple files inside it, but
		// the walk never enumerates them, so the count must stay at 1 (one
		// PRUNED DIRECTORY), not 3 (one per file it happens to contain).
		fs.mkdirSync(path.join(dir, "generated"));
		fs.writeFileSync(
			path.join(dir, "generated", "one.ts"),
			"export const one = 1;\n",
		);
		fs.writeFileSync(
			path.join(dir, "generated", "two.ts"),
			"export const two = 2;\n",
		);
		fs.mkdirSync(path.join(dir, "generated", "nested"));
		fs.writeFileSync(
			path.join(dir, "generated", "nested", "three.ts"),
			"export const three = 3;\n",
		);
		return dir;
	}

	it("sync walk: one generated/ directory with three files inside counts as 1 dir skip, 0 file skips", () => {
		const dir = createDirSkipTree();
		const result = collectSourceFilesWithBudget(dir);

		expect(result.files).toEqual([path.join(dir, "alpha.ts")]);
		expect(result.generatedDirSkips).toBe(1);
		expect(result.generatedOrArtifactSkips).toBe(0);
		expect(result.buildArtifactSkips).toBe(0);

		const summary = latencyEntries.find(
			(e) => e.phase === "source_walk_skip_summary",
		);
		expect(summary).toBeDefined();
		expect(summary?.metadata).toEqual({
			generatedOrArtifactSkips: 0,
			buildArtifactSkips: 0,
			generatedDirSkips: 1,
			generatedNameOverrides: 0,
			generatedNameOnlySkips: 0,
		});
	});

	it("async walk: agrees with the sync walk on the directory skip count", async () => {
		const dir = createDirSkipTree();
		const result = await collectSourceFilesWithBudgetAsync(dir);

		expect(result.files).toEqual([path.join(dir, "alpha.ts")]);
		expect(result.generatedDirSkips).toBe(1);
	});

	it("multiple pruned directories each count once, regardless of how many files they hold", () => {
		const dir = mkTempDir();
		fs.mkdirSync(path.join(dir, "generated"));
		fs.writeFileSync(path.join(dir, "generated", "a.ts"), "export {};\n");
		fs.mkdirSync(path.join(dir, "codegen"));
		fs.writeFileSync(path.join(dir, "codegen", "b.ts"), "export {};\n");
		fs.writeFileSync(path.join(dir, "codegen", "c.ts"), "export {};\n");

		const result = collectSourceFilesWithBudget(dir);

		expect(result.files).toEqual([]);
		expect(result.generatedDirSkips).toBe(2);
	});

	it("a directory that merely contains generated-named FILES (not itself a generated-named dir) is not counted here", () => {
		// Contrast case: `src/` is not a generated-artifact directory name, so
		// it is walked into normally — any skips inside it are FILE-level
		// (generatedOrArtifactSkips), not a directory skip.
		const dir = mkTempDir();
		fs.mkdirSync(path.join(dir, "src"));
		fs.writeFileSync(
			path.join(dir, "src", "gen.ts"),
			"// Code generated by tool. DO NOT EDIT.\nexport {};\n",
		);

		const result = collectSourceFilesWithBudget(dir);

		expect(result.generatedDirSkips).toBe(0);
		expect(result.generatedOrArtifactSkips).toBe(1);
	});
});

// #1107 phase 2 item 3: the content-probe escape hatch. A file matching a
// generated NAME pattern is no longer skipped on the name alone — it is
// skipped only when corroborating evidence confirms it (a higher-precedence
// source sibling, or a generated-code header in the first 4 KB); with
// NEITHER, it is now KEPT and counted under `generatedNameOverrides`.
describe("content-probe escape hatch matrix (#1107 phase 2 item 3)", () => {
	it("fail-then-pass: a gen-named file with NEITHER a source sibling NOR a generated header is KEPT (was silently dropped pre-#1107-phase-2)", () => {
		const dir = mkTempDir();
		// Matches GENERATED_FILE_PATTERNS' `/(^|[._-])gen([._-])/` rule; plain
		// hand-written content, no recognized generated-code banner, no `.js`/
		// other sibling anywhere near it.
		fs.writeFileSync(
			path.join(dir, "gen.ts"),
			"export function realHandWrittenFn() {\n\treturn 42;\n}\n",
		);

		const result = collectSourceFilesWithBudget(dir);

		// PASS (post-#1107-phase-2): kept, and the rescue is observable.
		expect(result.files).toEqual([path.join(dir, "gen.ts")]);
		expect(result.generatedNameOverrides).toBe(1);
		expect(result.generatedOrArtifactSkips).toBe(0);
		// FAIL (pre-#1107-phase-2 / master): the same fixture used to assert
		// `result.files` was `[]` and `generatedOrArtifactSkips` was `1` — this
		// exact scenario is #1107's invisible-coverage-hole class, and this
		// test is the fail-then-pass proof the escape hatch fixes it.
	});

	it("gen-named + source-twin evidence: still skipped (a real compiled artifact)", () => {
		const dir = mkTempDir();
		// `plan.gen.js` looks generated by name AND has a higher-precedence
		// `.ts` twin sitting next to it — the strongest evidence class, and it
		// alone is enough to skip without ever probing content.
		fs.writeFileSync(
			path.join(dir, "plan.gen.ts"),
			"export function planFn() {\n\treturn 1;\n}\n",
		);
		fs.writeFileSync(
			path.join(dir, "plan.gen.js"),
			"exports.planFn = function () { return 1; };\n",
		);

		const result = collectSourceFilesWithBudget(dir);

		// plan.gen.js: skipped via the sibling probe (a build artifact), never
		// even reaching the generated-name classification.
		expect(result.files).not.toContain(path.join(dir, "plan.gen.js"));
		expect(result.buildArtifactSkips).toBe(1);
		// plan.gen.ts itself is also a WEAK name match (contains ".gen.") but
		// has no source sibling of its own and no generated header — it is the
		// escape hatch's override case, kept and counted, same as the
		// standalone `gen.ts` fixture above.
		expect(result.files).toContain(path.join(dir, "plan.gen.ts"));
		expect(result.generatedNameOverrides).toBe(1);
	});

	it("gen-named + generated-header evidence: still skipped", () => {
		const dir = mkTempDir();
		fs.writeFileSync(
			path.join(dir, "gen.ts"),
			"// This file was automatically generated.\nexport function genFn() {\n\treturn 1;\n}\n",
		);

		const result = collectSourceFilesWithBudget(dir);

		expect(result.files).toEqual([]);
		expect(result.generatedOrArtifactSkips).toBe(1);
		expect(result.generatedNameOverrides).toBe(0);
		// Confirmed by content evidence, not trusted on the name alone — not
		// part of the "unconfirmed" bucket a tool-facing notice keys off.
		expect(result.generatedNameOnlySkips).toBe(0);
	});

	it("lockfile: always skipped regardless of the escape hatch (strong evidence, no probe)", () => {
		const dir = mkTempDir();
		fs.writeFileSync(
			path.join(dir, "package-lock.json"),
			JSON.stringify({ name: "x", lockfileVersion: 3 }),
		);
		fs.writeFileSync(path.join(dir, "app.ts"), "export const app = 1;\n");

		const result = collectSourceFilesWithBudget(dir, {
			extensions: [".ts", ".json"],
		});

		expect(result.files).toEqual([path.join(dir, "app.ts")]);
		expect(result.generatedOrArtifactSkips).toBe(1);
		expect(result.generatedNameOverrides).toBe(0);
		// STRONG evidence (a known lockfile basename) — not the unconfirmed
		// "name-only" bucket either.
		expect(result.generatedNameOnlySkips).toBe(0);
	});

	it("a WEAK name-only skip with NO header probe available IS counted as the unconfirmed bucket (the residual at-risk case)", () => {
		const dir = mkTempDir();
		fs.writeFileSync(
			path.join(dir, "gen.ts"),
			"export function realHandWrittenFn() {\n\treturn 42;\n}\n",
		);

		// Explicitly opting out of the header probe reproduces the pre-#1107
		// trust-the-name behavior for this one WEAK match — the one case
		// where classifyGeneratedOrArtifactDetailed cannot evaluate evidence
		// (b) at all, so it falls back to skipping (not the escape hatch) and
		// is counted as "name-only" (unconfirmed).
		const result = collectSourceFilesWithBudget(dir, {
			inspectGeneratedHeaders: false,
		});

		expect(result.files).toEqual([]);
		expect(result.generatedOrArtifactSkips).toBe(1);
		expect(result.generatedNameOnlySkips).toBe(1);
		expect(result.generatedNameOverrides).toBe(0);
	});

	// #1107 phase 2 review round 2 (P2, maintainer decision: KEEP min/bundle/
	// chunk in the STRONG tier). The escape hatch's evidence checks are
	// structurally dead for this class: minifiers strip banners (the header
	// leg never confirms), and the sibling probe looks for `app.min.ts`
	// (never `app.js` at a DIFFERENT stem), so the real source twin is
	// unreachable by that check. Both dead legs would make this class a
	// PERMANENT override under the WEAK tier — never re-confirmed — so it is
	// excluded from WEAK eligibility entirely and always skipped, like a
	// lockfile.
	it("fail-then-pass: app.min.js next to app.js is skipped unconditionally (STRONG tier), never an override", () => {
		const dir = mkTempDir();
		fs.writeFileSync(path.join(dir, "app.ts"), "export const app = 1;\n");
		fs.writeFileSync(path.join(dir, "app.js"), "exports.app = 1;\n");
		// The minified bundle: no generated-code header (minifiers strip
		// banners), and its "sibling" probe target would be `app.min.ts` —
		// which does not exist — never `app.ts` at the different stem.
		fs.writeFileSync(
			path.join(dir, "app.min.js"),
			"const app=1;module.exports={app:app};",
		);

		const result = collectSourceFilesWithBudget(dir);

		// PASS (post-review-round-2): app.min.js is skipped, and it is
		// counted under the STRONG-evidence skip counter, NEVER as a rescued
		// override — before this fix, with min/bundle/chunk still in the WEAK
		// tier, this exact fixture was kept and counted under
		// `generatedNameOverrides` (empirically proven by review: a real
		// minified bundle got indexed as if it were hand-written source).
		expect(result.files).not.toContain(path.join(dir, "app.min.js"));
		expect(result.generatedNameOverrides).toBe(0);
		expect(result.generatedOrArtifactSkips).toBeGreaterThanOrEqual(1);
		// Not the "unconfirmed name-only" bucket either — STRONG evidence
		// needs no probe and is never at-risk.
		expect(result.generatedNameOnlySkips).toBe(0);
		// app.js itself is still skipped separately, via the ordinary
		// sibling-source probe (app.ts shadows it) — unrelated to this case.
		expect(result.files).not.toContain(path.join(dir, "app.js"));
		expect(result.files).toContain(path.join(dir, "app.ts"));
	});

	it("bundle/chunk output is also STRONG tier, never an override", () => {
		const dir = mkTempDir();
		fs.writeFileSync(
			path.join(dir, "vendor.bundle.js"),
			"/* no banner */ (function(){})();",
		);
		fs.writeFileSync(
			path.join(dir, "runtime.chunk.js"),
			"/* no banner */ (function(){})();",
		);

		const result = collectSourceFilesWithBudget(dir);

		expect(result.files).toEqual([]);
		expect(result.generatedOrArtifactSkips).toBe(2);
		expect(result.generatedNameOverrides).toBe(0);
		expect(result.generatedNameOnlySkips).toBe(0);
	});

	it("async walk agrees with the sync walk on the override verdict", async () => {
		const dir = mkTempDir();
		fs.writeFileSync(
			path.join(dir, "gen.ts"),
			"export function realHandWrittenFn() {\n\treturn 42;\n}\n",
		);

		const result = await collectSourceFilesWithBudgetAsync(dir);

		expect(result.files).toEqual([path.join(dir, "gen.ts")]);
		expect(result.generatedNameOverrides).toBe(1);
	});

	it("a non-matching, ordinary hand-written file is neither a skip nor an override", () => {
		const dir = mkTempDir();
		fs.writeFileSync(
			path.join(dir, "widget.ts"),
			"export function widgetFn() {\n\treturn 1;\n}\n",
		);

		const result = collectSourceFilesWithBudget(dir);

		expect(result.files).toEqual([path.join(dir, "widget.ts")]);
		expect(result.generatedNameOverrides).toBe(0);
		expect(result.generatedOrArtifactSkips).toBe(0);
	});
});
