#!/usr/bin/env node

import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { createRuntimeBuilder } from "../../../scripts/runtime-builder.mjs";

export const { buildRuntime, validateEagerGraph, validateGeneratedFiles, publishRuntime } = createRuntimeBuilder({
  packageRoot: resolve(dirname(fileURLToPath(import.meta.url)), ".."),
  temporaryPrefix: ".pi-chat",
  banner: [
    "// @generated by scripts/build-runtime.mjs; do not edit.",
    "// @ts-nocheck -- the generated entry uses a .ts extension for Pi's Jiti loader.",
  ].join("\n"),
  forbiddenEagerInputs: [
    "src/network.ts",
    "src/directory-network.ts",
    "src/menu.ts",
    "src/chat-view.ts",
    "src/widget.ts",
  ],
  forbiddenEagerExternals: ["@narumitw/pi-tui-kit"],
});

const invokedPath = process.argv[1] ? pathToFileURL(resolve(process.argv[1])).href : undefined;
if (invokedPath === import.meta.url) await buildRuntime();
