/**
 * Equivalence guards for the walker consolidation (refs #191, "unify the
 * three divergent source walkers").
 *
 * `collectSourceFiles`/`collectSourceFilesAsync` (source-filter.ts),
 * `collectSourceFilesForWarmup` (language-profile.ts), and
 * `countSourceFilesWithinLimit`/`countSourceFilesWithinLimitAsync`
 * (startup-scan.ts) now all delegate their "should I recurse into this
 * directory" decision to the shared `shouldRecurseIntoDir` in
 * `source-walker.ts`, and their `readdirSync` boilerplate to
 * `readDirEntriesSafe`. Everything else (extension/regex rules,
 * build-artifact + generated-header filtering, hard caps, sync-vs-async
 * shape) stayed caller-specific by design.
 *
 * This suite pins a single fixture tree that deliberately exercises every
 * point where the three callers are SUPPOSED to disagree — extension sets,
 * generated-artifact-directory skipping, build-artifact shadowing, and
 * generated-header content sniffing — and asserts each walker's exact,
 * historical output. A consolidation bug that accidentally shares behavior
 * across callers (e.g. warmup starts skipping `generated/` directories, or
 * the startup-scan counter starts respecting build-artifact shadowing) would
 * change one of these sets without changing the others, and this test would
 * catch it.
 */

import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { _resetGeneratedArtifactCaches } from "../../clients/generated-artifacts.js";
import { collectSourceFilesForWarmup } from "../../clients/language-profile.js";
import {
	collectSourceFiles,
	collectSourceFilesAsync,
} from "../../clients/source-filter.js";
import {
	countSourceFilesWithinLimit,
	countSourceFilesWithinLimitAsync,
} from "../../clients/startup-scan.js";
import { removeTempDirSync } from "./test-utils.js";

let tmpDir: string;

/**
 * Builds one fixture tree shared by all three walkers, with a file placed at
 * every point of known caller divergence:
 *
 *  - `a.ts`, `b.py`        — plain source, kept by every walker.
 *  - `c.vue`, `d.java`      — supported-kind sources kept by both walkers.
 *  - `vendor/e.ts`          — excluded by `.gitignore` for every walker.
 *  - `node_modules/f.ts`    — excluded by the shared default exclude list for every walker.
 *  - `generated/g.ts`      — a `GENERATED_DIR_NAMES` directory. Only
 *                             source-filter's collectors skip generated-
 *                             artifact directories; warmup and startup-scan
 *                             never checked for this and must keep walking in.
 *  - `shadow.ts`/`shadow.js` — `shadow.js` is a build artifact of
 *                             `shadow.ts`. Only source-filter's collectors
 *                             drop shadowed siblings.
 *  - `banner.js`            — has a `@generated` content header. Only
 *                             source-filter's collectors inspect file
 *                             content for generated banners.
 */
function buildFixture(root: string): void {
	fs.writeFileSync(path.join(root, ".gitignore"), "vendor/\n");
	fs.writeFileSync(path.join(root, "a.ts"), "export const a = 1;\n");
	fs.writeFileSync(path.join(root, "b.py"), "b = 1\n");
	fs.writeFileSync(path.join(root, "c.vue"), "<template></template>\n");
	fs.writeFileSync(path.join(root, "d.java"), "class D {}\n");

	fs.mkdirSync(path.join(root, "vendor"));
	fs.writeFileSync(path.join(root, "vendor", "e.ts"), "export const e = 1;\n");

	fs.mkdirSync(path.join(root, "node_modules", "dep"), { recursive: true });
	fs.writeFileSync(
		path.join(root, "node_modules", "dep", "f.ts"),
		"export const f = 1;\n",
	);

	fs.mkdirSync(path.join(root, "generated"));
	fs.writeFileSync(
		path.join(root, "generated", "g.ts"),
		"export const g = 1;\n",
	);

	fs.writeFileSync(path.join(root, "shadow.ts"), "export const s = 1;\n");
	fs.writeFileSync(path.join(root, "shadow.js"), "exports.s = 1;\n");

	fs.writeFileSync(
		path.join(root, "banner.js"),
		"// @generated by codegen — do not edit\nexports.x = 1;\n",
	);
}

function relFiles(root: string, files: string[]): string[] {
	return files.map((f) => path.relative(root, f).replace(/\\/g, "/")).sort();
}

beforeEach(() => {
	tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "pi-lens-walker-eq-"));
	buildFixture(tmpDir);
	_resetGeneratedArtifactCaches();
});

afterEach(() => {
	removeTempDirSync(tmpDir);
	_resetGeneratedArtifactCaches();
});

describe("collectSourceFiles / collectSourceFilesAsync — preserved semantics", () => {
	// Build-artifact shadowing + generated-dir skip + generated-header content
	// sniffing are all still applied. The default extension set now derives every
	// supported kind, so Java is kept alongside the previously-scanned files.
	const expected = ["a.ts", "b.py", "c.vue", "d.java", "shadow.ts"];

	it("sync collector keeps exactly the expected set", () => {
		const files = collectSourceFiles(tmpDir);
		expect(relFiles(tmpDir, files)).toEqual(expected);
	});

	it("async collector keeps the identical set as the sync collector", async () => {
		const files = await collectSourceFilesAsync(tmpDir);
		expect(relFiles(tmpDir, files)).toEqual(expected);
	});
});

describe("collectSourceFilesForWarmup — preserved semantics", () => {
	// No build-artifact shadowing, no generated-content sniffing, and
	// `generated/` is walked into (unlike source-filter). Its extension set now
	// derives every supported kind, including both Java and Vue.
	const expected = [
		"a.ts",
		"b.py",
		"banner.js",
		"c.vue",
		"d.java",
		"generated/g.ts",
		"shadow.js",
		"shadow.ts",
	];

	it("keeps exactly the expected set — diverges from source-filter by design", async () => {
		const files = await collectSourceFilesForWarmup(tmpDir);
		expect(relFiles(tmpDir, files)).toEqual(expected);
	});

	it("still hard-caps at maxFiles (unrelated to the shared walker change)", async () => {
		const files = await collectSourceFilesForWarmup(tmpDir, 3);
		expect(files).toHaveLength(3);
	});
});

describe("countSourceFilesWithinLimit(Async) — preserved semantics", () => {
	// SOURCE_FILE_PATTERN has no .vue or .java, so both are excluded; no
	// build-artifact/generated-header awareness, and `generated/` is counted
	// (unlike source-filter).
	const EXPECTED_COUNT = 6; // a.ts, b.py, generated/g.ts, shadow.ts, shadow.js, banner.js

	it("sync counter matches the hand-derived expected count", () => {
		const count = countSourceFilesWithinLimit(tmpDir, 1000);
		expect(count).toBe(EXPECTED_COUNT);
	});

	it("async counter matches the sync counter on an under-limit tree", async () => {
		const count = await countSourceFilesWithinLimitAsync(tmpDir, 1000);
		expect(count).toBe(EXPECTED_COUNT);
	});
});

describe("shared exclusion behavior — identical across all three walkers", () => {
	it("every walker excludes the gitignored dir and the default-excluded dir", async () => {
		const sync = collectSourceFiles(tmpDir);
		const async_ = await collectSourceFilesAsync(tmpDir);
		const warmup = await collectSourceFilesForWarmup(tmpDir);
		const count = countSourceFilesWithinLimit(tmpDir, 1000);

		for (const files of [sync, async_, warmup]) {
			expect(files.some((f) => f.includes("vendor"))).toBe(false);
			expect(files.some((f) => f.includes("node_modules"))).toBe(false);
		}
		// The count-only walker can't be asserted the same way, but its total
		// (6) already excludes vendor/e.ts and node_modules/f.ts — if either
		// leaked in, EXPECTED_COUNT above would be 7 or 8, not 6.
		expect(count).toBe(6);
	});
});
