import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const packageDir = path.resolve(__dirname, '..');
const repoRoot = path.resolve(packageDir, '../..');

const sourcePath = path.join(repoRoot, 'README.md');
const targetPath = path.join(packageDir, 'README.md');

const repoBlobBase = 'https://github.com/RunMintOn/pi-gaurd-sandbox/blob/main/';
const repoRawBase = 'https://raw.githubusercontent.com/RunMintOn/pi-gaurd-sandbox/main/';
const imageExt = /\.(png|jpe?g|gif|webp|svg)$/i;

function encodeRepoPath(value) {
  return value
    .split('/')
    .map((segment) => encodeURIComponent(segment))
    .join('/');
}

function rewriteUrl(url, kind) {
  if (!url || /^(?:[a-z]+:|#)/i.test(url)) return url;
  const clean = url.replace(/^\.\//, '');
  const base = kind === 'image' || imageExt.test(clean) ? repoRawBase : repoBlobBase;
  return base + encodeRepoPath(clean);
}

let readme = readFileSync(sourcePath, 'utf8');

readme = readme.replace(/<img\s+([^>]*?)src=["']([^"']+)["']([^>]*)>/gi, (_m, before, src, after) => {
  return `<img ${before}src="${rewriteUrl(src, 'image')}"${after}>`;
});

readme = readme.replace(/(!?)\[([^\]]*)\]\(([^)]+)\)/g, (_m, bang, text, url) => {
  const trimmed = url.trim();
  const kind = bang ? 'image' : 'link';
  return `${bang}[${text}](${rewriteUrl(trimmed, kind)})`;
});

const banner = '<!-- Generated from ../../README.md by scripts/sync-readme.mjs. Do not edit this file directly. -->\n\n';
mkdirSync(path.dirname(targetPath), { recursive: true });
writeFileSync(targetPath, banner + readme);
