#!/usr/bin/env node

import { constants } from "node:fs";
import { access, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const packageRoot = path.resolve(fileURLToPath(new URL("..", import.meta.url)));
const webRoot = path.join(packageRoot, "src", "web");
const uiRoot = path.join(webRoot, "ui");
const checking = process.argv.includes("--check");
const temporaryRoot = checking ? await mkdtemp(path.join(tmpdir(), "pi-image-drop-")) : undefined;
const outputRoot = temporaryRoot ?? webRoot;
const assets = ["app.js", "state.js", "styles.css"];

try {
	await build({
		entryPoints: {
			app: path.join(uiRoot, "app.tsx"),
			state: path.join(uiRoot, "state.ts"),
			styles: path.join(uiRoot, "styles.css"),
		},
		bundle: true,
		minify: true,
		legalComments: "inline",
		format: "esm",
		jsx: "automatic",
		platform: "browser",
		target: ["es2022"],
		outdir: outputRoot,
		entryNames: "[name]",
		assetNames: "[name]",
		define: { "process.env.NODE_ENV": '"production"' },
		banner: {
			js: `/* Generated by scripts/build-web.mjs. Do not edit directly. */
const __webpack_nonce__ = typeof document === "undefined"
	? undefined
	: document.querySelector('meta[name="csp-nonce"]')?.content;`,
			css: "/* Generated by scripts/build-web.mjs. Do not edit directly. */",
		},
	});
	for (const name of assets) {
		const outputPath = path.join(outputRoot, name);
		const normalized = (await readFile(outputPath, "utf8")).replace(/[\t ]+$/gm, "");
		await writeFile(outputPath, normalized);
	}
	if (checking) {
		for (const name of assets) {
			const expected = await readFile(path.join(outputRoot, name));
			let actual;
			try {
				await access(path.join(webRoot, name), constants.R_OK);
				actual = await readFile(path.join(webRoot, name));
			} catch {
				throw new Error(`${name} is missing; run npm run build:web.`);
			}
			if (!actual.equals(expected)) {
				throw new Error(`${name} is stale; run npm run build:web.`);
			}
		}
		console.log("Pi Image Drop browser assets are current.");
	}
} finally {
	if (temporaryRoot) await rm(temporaryRoot, { recursive: true, force: true });
}
